// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: activity.proto

package activityclient

import (
	"context"

	"pallink/activity/rpc/activity"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	ActivityInfo             = activity.ActivityInfo
	CreateActivityRequest    = activity.CreateActivityRequest
	EnrollActivityRequest    = activity.EnrollActivityRequest
	EnrollActivityResponse   = activity.EnrollActivityResponse
	GetActivityDetailRequest = activity.GetActivityDetailRequest
	GetActivityListRequest   = activity.GetActivityListRequest
	GetActivityListResponse  = activity.GetActivityListResponse

	Activity interface {
		CreateActivity(ctx context.Context, in *CreateActivityRequest, opts ...grpc.CallOption) (*ActivityInfo, error)
		GetActivityList(ctx context.Context, in *GetActivityListRequest, opts ...grpc.CallOption) (*GetActivityListResponse, error)
		GetActivityDetail(ctx context.Context, in *GetActivityDetailRequest, opts ...grpc.CallOption) (*ActivityInfo, error)
		EnrollActivity(ctx context.Context, in *EnrollActivityRequest, opts ...grpc.CallOption) (*EnrollActivityResponse, error)
	}

	defaultActivity struct {
		cli zrpc.Client
	}
)

func NewActivity(cli zrpc.Client) Activity {
	return &defaultActivity{
		cli: cli,
	}
}

func (m *defaultActivity) CreateActivity(ctx context.Context, in *CreateActivityRequest, opts ...grpc.CallOption) (*ActivityInfo, error) {
	client := activity.NewActivityClient(m.cli.Conn())
	return client.CreateActivity(ctx, in, opts...)
}

func (m *defaultActivity) GetActivityList(ctx context.Context, in *GetActivityListRequest, opts ...grpc.CallOption) (*GetActivityListResponse, error) {
	client := activity.NewActivityClient(m.cli.Conn())
	return client.GetActivityList(ctx, in, opts...)
}

func (m *defaultActivity) GetActivityDetail(ctx context.Context, in *GetActivityDetailRequest, opts ...grpc.CallOption) (*ActivityInfo, error) {
	client := activity.NewActivityClient(m.cli.Conn())
	return client.GetActivityDetail(ctx, in, opts...)
}

func (m *defaultActivity) EnrollActivity(ctx context.Context, in *EnrollActivityRequest, opts ...grpc.CallOption) (*EnrollActivityResponse, error) {
	client := activity.NewActivityClient(m.cli.Conn())
	return client.EnrollActivity(ctx, in, opts...)
}
