apiVersion: v1
kind: Secret
metadata:
  name: pallink-secrets
type: Opaque
stringData:
  postgres-user: pallink
  postgres-password: pallink
  postgres-db: pallink
  rabbitmq-user: admin
  rabbitmq-password: pallink
  pghero-username: admin
  pghero-password: pallink
  pghero-database-url: postgres://pallink:pallink@postgres:5432/pallink
  grafana-admin-user: admin
  grafana-admin-password: pallink
