// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countConversations = `-- name: CountConversations :one
SELECT count(*)
FROM im_conversation_member
WHERE user_id = $1
`

func (q *Queries) CountConversations(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countConversations, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const ensureConversationMember = `-- name: EnsureConversationMember :exec
INSERT INTO im_conversation_member (conversation_id, user_id, last_read_msg_id, updated_at)
VALUES ($1, $2, 0, now())
ON CONFLICT (conversation_id, user_id)
DO NOTHING
`

type EnsureConversationMemberParams struct {
	ConversationID int64
	UserID         int64
}

func (q *Queries) EnsureConversationMember(ctx context.Context, arg EnsureConversationMemberParams) error {
	_, err := q.db.Exec(ctx, ensureConversationMember, arg.ConversationID, arg.UserID)
	return err
}

const getConversationMember = `-- name: GetConversationMember :one
SELECT conversation_id, user_id, last_read_msg_id, updated_at
FROM im_conversation_member
WHERE conversation_id = $1
  AND user_id = $2
`

type GetConversationMemberParams struct {
	ConversationID int64
	UserID         int64
}

type GetConversationMemberRow struct {
	ConversationID int64
	UserID         int64
	LastReadMsgID  int64
	UpdatedAt      pgtype.Timestamptz
}

func (q *Queries) GetConversationMember(ctx context.Context, arg GetConversationMemberParams) (GetConversationMemberRow, error) {
	row := q.db.QueryRow(ctx, getConversationMember, arg.ConversationID, arg.UserID)
	var i GetConversationMemberRow
	err := row.Scan(
		&i.ConversationID,
		&i.UserID,
		&i.LastReadMsgID,
		&i.UpdatedAt,
	)
	return i, err
}

const getConversationSummary = `-- name: GetConversationSummary :one
SELECT c.id,
       (CASE WHEN c.user1_id = $1 THEN c.user2_id ELSE c.user1_id END)::BIGINT AS peer_user_id,
       COALESCE(m.id, 0) AS last_message_id,
       COALESCE(m.sender_id, 0) AS last_sender_id,
       COALESCE(m.content, '') AS last_message,
       COALESCE(m.created_at, c.created_at) AS last_message_at,
       c.created_at,
       (
         SELECT count(*)
         FROM im_message imx
         WHERE imx.conversation_id = c.id
           AND imx.id > cm.last_read_msg_id
           AND imx.sender_id <> $1
       ) AS unread_count
FROM im_conversation_member cm
JOIN im_conversation c ON c.id = cm.conversation_id
LEFT JOIN LATERAL (
    SELECT id, sender_id, content, created_at
    FROM im_message
    WHERE conversation_id = c.id
    ORDER BY id DESC
    LIMIT 1
) m ON true
WHERE cm.user_id = $1
  AND c.id = $2
`

type GetConversationSummaryParams struct {
	UserID         int64
	ConversationID int64
}

type GetConversationSummaryRow struct {
	ID            int64
	PeerUserID    int64
	LastMessageID int64
	LastSenderID  int64
	LastMessage   string
	LastMessageAt pgtype.Timestamptz
	CreatedAt     pgtype.Timestamptz
	UnreadCount   int64
}

func (q *Queries) GetConversationSummary(ctx context.Context, arg GetConversationSummaryParams) (GetConversationSummaryRow, error) {
	row := q.db.QueryRow(ctx, getConversationSummary, arg.UserID, arg.ConversationID)
	var i GetConversationSummaryRow
	err := row.Scan(
		&i.ID,
		&i.PeerUserID,
		&i.LastMessageID,
		&i.LastSenderID,
		&i.LastMessage,
		&i.LastMessageAt,
		&i.CreatedAt,
		&i.UnreadCount,
	)
	return i, err
}

const getLatestMessageID = `-- name: GetLatestMessageID :one
SELECT id
FROM im_message
WHERE conversation_id = $1
ORDER BY id DESC
LIMIT 1
`

func (q *Queries) GetLatestMessageID(ctx context.Context, conversationID int64) (int64, error) {
	row := q.db.QueryRow(ctx, getLatestMessageID, conversationID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getMessageInConversation = `-- name: GetMessageInConversation :one
SELECT id
FROM im_message
WHERE conversation_id = $1
  AND id = $2
`

type GetMessageInConversationParams struct {
	ConversationID int64
	MessageID      int64
}

func (q *Queries) GetMessageInConversation(ctx context.Context, arg GetMessageInConversationParams) (int64, error) {
	row := q.db.QueryRow(ctx, getMessageInConversation, arg.ConversationID, arg.MessageID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertMessage = `-- name: InsertMessage :one
INSERT INTO im_message (conversation_id, sender_id, content, audit_status, created_at)
VALUES ($1, $2, $3, 1, now())
RETURNING id, conversation_id, sender_id, content, audit_status, created_at
`

type InsertMessageParams struct {
	ConversationID int64
	SenderID       int64
	Content        string
}

func (q *Queries) InsertMessage(ctx context.Context, arg InsertMessageParams) (ImMessage, error) {
	row := q.db.QueryRow(ctx, insertMessage, arg.ConversationID, arg.SenderID, arg.Content)
	var i ImMessage
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.SenderID,
		&i.Content,
		&i.AuditStatus,
		&i.CreatedAt,
	)
	return i, err
}

const listConversations = `-- name: ListConversations :many
SELECT c.id,
       (CASE WHEN c.user1_id = $1 THEN c.user2_id ELSE c.user1_id END)::BIGINT AS peer_user_id,
       COALESCE(m.id, 0) AS last_message_id,
       COALESCE(m.sender_id, 0) AS last_sender_id,
       COALESCE(m.content, '') AS last_message,
       COALESCE(m.created_at, c.created_at) AS last_message_at,
       c.created_at,
       (
         SELECT count(*)
         FROM im_message imx
         WHERE imx.conversation_id = c.id
           AND imx.id > cm.last_read_msg_id
           AND imx.sender_id <> $1
       ) AS unread_count
FROM im_conversation_member cm
JOIN im_conversation c ON c.id = cm.conversation_id
LEFT JOIN LATERAL (
    SELECT id, sender_id, content, created_at
    FROM im_message
    WHERE conversation_id = c.id
    ORDER BY id DESC
    LIMIT 1
) m ON true
WHERE cm.user_id = $1
ORDER BY COALESCE(m.id, 0) DESC, c.id DESC
LIMIT $3 OFFSET $2
`

type ListConversationsParams struct {
	UserID     int64
	PageOffset int32
	PageLimit  int32
}

type ListConversationsRow struct {
	ID            int64
	PeerUserID    int64
	LastMessageID int64
	LastSenderID  int64
	LastMessage   string
	LastMessageAt pgtype.Timestamptz
	CreatedAt     pgtype.Timestamptz
	UnreadCount   int64
}

func (q *Queries) ListConversations(ctx context.Context, arg ListConversationsParams) ([]ListConversationsRow, error) {
	rows, err := q.db.Query(ctx, listConversations, arg.UserID, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListConversationsRow{}
	for rows.Next() {
		var i ListConversationsRow
		if err := rows.Scan(
			&i.ID,
			&i.PeerUserID,
			&i.LastMessageID,
			&i.LastSenderID,
			&i.LastMessage,
			&i.LastMessageAt,
			&i.CreatedAt,
			&i.UnreadCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessages = `-- name: ListMessages :many
SELECT id, conversation_id, sender_id, content, audit_status, created_at
FROM im_message
WHERE conversation_id = $1
  AND ($2 = 0 OR id < $2)
ORDER BY id DESC
LIMIT $3
`

type ListMessagesParams struct {
	ConversationID  int64
	BeforeMessageID interface{}
	PageLimit       int32
}

func (q *Queries) ListMessages(ctx context.Context, arg ListMessagesParams) ([]ImMessage, error) {
	rows, err := q.db.Query(ctx, listMessages, arg.ConversationID, arg.BeforeMessageID, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ImMessage{}
	for rows.Next() {
		var i ImMessage
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.SenderID,
			&i.Content,
			&i.AuditStatus,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateConversationReadCursor = `-- name: UpdateConversationReadCursor :execrows
UPDATE im_conversation_member
SET last_read_msg_id = GREATEST(last_read_msg_id, $1),
    updated_at = now()
WHERE conversation_id = $2
  AND user_id = $3
`

type UpdateConversationReadCursorParams struct {
	LastReadMsgID  int64
	ConversationID int64
	UserID         int64
}

func (q *Queries) UpdateConversationReadCursor(ctx context.Context, arg UpdateConversationReadCursorParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateConversationReadCursor, arg.LastReadMsgID, arg.ConversationID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertConversation = `-- name: UpsertConversation :one
INSERT INTO im_conversation (user1_id, user2_id, created_at)
VALUES ($1, $2, now())
ON CONFLICT (user1_id, user2_id)
DO UPDATE SET user1_id = EXCLUDED.user1_id
RETURNING id, user1_id, user2_id, created_at
`

type UpsertConversationParams struct {
	User1ID int64
	User2ID int64
}

func (q *Queries) UpsertConversation(ctx context.Context, arg UpsertConversationParams) (ImConversation, error) {
	row := q.db.QueryRow(ctx, upsertConversation, arg.User1ID, arg.User2ID)
	var i ImConversation
	err := row.Scan(
		&i.ID,
		&i.User1ID,
		&i.User2ID,
		&i.CreatedAt,
	)
	return i, err
}
