// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: activity.proto

package server

import (
	"context"

	"pallink/activity/rpc/activity"
	"pallink/activity/rpc/internal/logic"
	"pallink/activity/rpc/internal/svc"
)

type ActivityServer struct {
	svcCtx *svc.ServiceContext
	activity.UnimplementedActivityServer
}

func NewActivityServer(svcCtx *svc.ServiceContext) *ActivityServer {
	return &ActivityServer{
		svcCtx: svcCtx,
	}
}

func (s *ActivityServer) CreateActivity(ctx context.Context, in *activity.CreateActivityRequest) (*activity.ActivityInfo, error) {
	l := logic.NewCreateActivityLogic(ctx, s.svcCtx)
	return l.CreateActivity(in)
}

func (s *ActivityServer) GetActivityList(ctx context.Context, in *activity.GetActivityListRequest) (*activity.GetActivityListResponse, error) {
	l := logic.NewGetActivityListLogic(ctx, s.svcCtx)
	return l.GetActivityList(in)
}

func (s *ActivityServer) GetActivityDetail(ctx context.Context, in *activity.GetActivityDetailRequest) (*activity.ActivityInfo, error) {
	l := logic.NewGetActivityDetailLogic(ctx, s.svcCtx)
	return l.GetActivityDetail(in)
}

func (s *ActivityServer) EnrollActivity(ctx context.Context, in *activity.EnrollActivityRequest) (*activity.EnrollActivityResponse, error) {
	l := logic.NewEnrollActivityLogic(ctx, s.svcCtx)
	return l.EnrollActivity(in)
}
