// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Activity struct {
	ID            int64
	CreatorID     int64
	Title         string
	Description   pgtype.Text
	Location      string
	StartTime     pgtype.Timestamptz
	EndTime       pgtype.Timestamptz
	MaxPeople     int32
	CurrentPeople int32
	Status        int16
	AuditStatus   int16
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

type ActivityComment struct {
	ID          int64
	ActivityID  int64
	UserID      int64
	ParentID    pgtype.Int8
	Content     string
	AuditStatus int16
	CreatedAt   pgtype.Timestamptz
}

type Enrollment struct {
	ID          int64
	ActivityID  int64
	UserID      int64
	Status      int16
	EnrollTime  pgtype.Timestamptz
	CheckinTime pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type ImConversation struct {
	ID        int64
	User1ID   int64
	User2ID   int64
	CreatedAt pgtype.Timestamptz
}

type ImConversationMember struct {
	ID             int64
	ConversationID int64
	UserID         int64
	LastReadMsgID  int64
	UpdatedAt      pgtype.Timestamptz
}

type ImMessage struct {
	ID             int64
	ConversationID int64
	SenderID       int64
	Content        string
	AuditStatus    int16
	CreatedAt      pgtype.Timestamptz
}

type Notification struct {
	ID         int64
	UserID     int64
	ActorID    int64
	Type       string
	ActivityID pgtype.Int8
	CommentID  pgtype.Int8
	ParentID   pgtype.Int8
	Content    string
	CreatedAt  pgtype.Timestamptz
	ReadAt     pgtype.Timestamptz
}

type User struct {
	ID           int64
	Mobile       string
	PasswordHash string
	Nickname     string
	Avatar       string
	AuditStatus  int16
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}
