// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countNotifications = `-- name: CountNotifications :one
SELECT count(*)
FROM notification
WHERE user_id = $1
  AND (NOT $2 OR read_at IS NULL)
`

type CountNotificationsParams struct {
	UserID     int64
	UnreadOnly interface{}
}

func (q *Queries) CountNotifications(ctx context.Context, arg CountNotificationsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countNotifications, arg.UserID, arg.UnreadOnly)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertNotification = `-- name: InsertNotification :exec
INSERT INTO notification (user_id, actor_id, type, activity_id, comment_id, parent_id, content, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, now())
`

type InsertNotificationParams struct {
	UserID     int64
	ActorID    int64
	Type       string
	ActivityID pgtype.Int8
	CommentID  pgtype.Int8
	ParentID   pgtype.Int8
	Content    string
}

func (q *Queries) InsertNotification(ctx context.Context, arg InsertNotificationParams) error {
	_, err := q.db.Exec(ctx, insertNotification,
		arg.UserID,
		arg.ActorID,
		arg.Type,
		arg.ActivityID,
		arg.CommentID,
		arg.ParentID,
		arg.Content,
	)
	return err
}

const listNotifications = `-- name: ListNotifications :many
SELECT id, user_id, actor_id, type,
       COALESCE(activity_id, 0) AS activity_id,
       COALESCE(comment_id, 0) AS comment_id,
       COALESCE(parent_id, 0) AS parent_id,
       content, created_at, read_at
FROM notification
WHERE user_id = $1
  AND (NOT $2 OR read_at IS NULL)
ORDER BY created_at DESC
LIMIT $4 OFFSET $3
`

type ListNotificationsParams struct {
	UserID     int64
	UnreadOnly interface{}
	PageOffset int32
	PageLimit  int32
}

type ListNotificationsRow struct {
	ID         int64
	UserID     int64
	ActorID    int64
	Type       string
	ActivityID int64
	CommentID  int64
	ParentID   int64
	Content    string
	CreatedAt  pgtype.Timestamptz
	ReadAt     pgtype.Timestamptz
}

func (q *Queries) ListNotifications(ctx context.Context, arg ListNotificationsParams) ([]ListNotificationsRow, error) {
	rows, err := q.db.Query(ctx, listNotifications,
		arg.UserID,
		arg.UnreadOnly,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListNotificationsRow{}
	for rows.Next() {
		var i ListNotificationsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ActorID,
			&i.Type,
			&i.ActivityID,
			&i.CommentID,
			&i.ParentID,
			&i.Content,
			&i.CreatedAt,
			&i.ReadAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markReadAll = `-- name: MarkReadAll :exec
UPDATE notification
SET read_at = now()
WHERE user_id = $1
  AND read_at IS NULL
`

func (q *Queries) MarkReadAll(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, markReadAll, userID)
	return err
}

const markReadOne = `-- name: MarkReadOne :exec
UPDATE notification
SET read_at = now()
WHERE user_id = $1
  AND id = $2
`

type MarkReadOneParams struct {
	UserID int64
	ID     int64
}

func (q *Queries) MarkReadOne(ctx context.Context, arg MarkReadOneParams) error {
	_, err := q.db.Exec(ctx, markReadOne, arg.UserID, arg.ID)
	return err
}
