// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countActivities = `-- name: CountActivities :one
SELECT count(*)
FROM activity a
LEFT JOIN enrollment e_filter ON e_filter.activity_id = a.id AND e_filter.user_id = $1 AND e_filter.status IN (1,2)
WHERE (NOT $2 OR a.creator_id = $3)
  AND (NOT $4 OR e_filter.id IS NOT NULL)
  AND ($5 = -1 OR a.status = $5)
  AND ($6 = -1 OR a.audit_status = $6)
  AND ($7 = '' OR a.title ILIKE '%' || $7 || '%' OR a.description ILIKE '%' || $7 || '%')
`

type CountActivitiesParams struct {
	EnrolledUserID int64
	UseCreator     interface{}
	CreatorID      int64
	UseEnrolled    interface{}
	Status         interface{}
	AuditStatus    interface{}
	Keyword        interface{}
}

func (q *Queries) CountActivities(ctx context.Context, arg CountActivitiesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countActivities,
		arg.EnrolledUserID,
		arg.UseCreator,
		arg.CreatorID,
		arg.UseEnrolled,
		arg.Status,
		arg.AuditStatus,
		arg.Keyword,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countComments = `-- name: CountComments :one
SELECT count(*)
FROM activity_comment
WHERE activity_id = $1
  AND (
    ($2 = 0 AND parent_id IS NULL)
    OR
    ($2 <> 0 AND parent_id = $2)
  )
  AND ($3 OR audit_status = 1)
`

type CountCommentsParams struct {
	ActivityID        int64
	ParentID          interface{}
	IncludeUnapproved interface{}
}

func (q *Queries) CountComments(ctx context.Context, arg CountCommentsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countComments, arg.ActivityID, arg.ParentID, arg.IncludeUnapproved)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countParticipants = `-- name: CountParticipants :one
SELECT count(*)
FROM enrollment
WHERE activity_id = $1
  AND status IN (1,2)
`

func (q *Queries) CountParticipants(ctx context.Context, activityID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countParticipants, activityID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createActivity = `-- name: CreateActivity :one
INSERT INTO activity (creator_id, title, description, location, start_time, end_time, max_people, current_people, status, audit_status, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, 0, 1, 0, now())
RETURNING id
`

type CreateActivityParams struct {
	CreatorID   int64
	Title       string
	Description pgtype.Text
	Location    string
	StartTime   pgtype.Timestamptz
	EndTime     pgtype.Timestamptz
	MaxPeople   int32
}

func (q *Queries) CreateActivity(ctx context.Context, arg CreateActivityParams) (int64, error) {
	row := q.db.QueryRow(ctx, createActivity,
		arg.CreatorID,
		arg.Title,
		arg.Description,
		arg.Location,
		arg.StartTime,
		arg.EndTime,
		arg.MaxPeople,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getActivityCreator = `-- name: GetActivityCreator :one
SELECT creator_id FROM activity WHERE id = $1
`

func (q *Queries) GetActivityCreator(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRow(ctx, getActivityCreator, id)
	var creator_id int64
	err := row.Scan(&creator_id)
	return creator_id, err
}

const getActivityDetail = `-- name: GetActivityDetail :one
SELECT a.id,
       a.creator_id,
       a.title,
       a.description,
       a.location,
       a.start_time,
       a.end_time,
       a.max_people,
       a.current_people,
       a.status,
       a.audit_status,
       a.created_at,
       CASE WHEN $1 = 0 THEN false
            ELSE EXISTS(
                SELECT 1 FROM enrollment e
                WHERE e.activity_id = a.id
                  AND e.user_id = $1
                  AND e.status IN (1,2)
            )
       END AS is_enrolled
FROM activity a
WHERE a.id = $2
`

type GetActivityDetailParams struct {
	ViewerUserID interface{}
	ID           int64
}

type GetActivityDetailRow struct {
	ID            int64
	CreatorID     int64
	Title         string
	Description   pgtype.Text
	Location      string
	StartTime     pgtype.Timestamptz
	EndTime       pgtype.Timestamptz
	MaxPeople     int32
	CurrentPeople int32
	Status        int16
	AuditStatus   int16
	CreatedAt     pgtype.Timestamptz
	IsEnrolled    interface{}
}

func (q *Queries) GetActivityDetail(ctx context.Context, arg GetActivityDetailParams) (GetActivityDetailRow, error) {
	row := q.db.QueryRow(ctx, getActivityDetail, arg.ViewerUserID, arg.ID)
	var i GetActivityDetailRow
	err := row.Scan(
		&i.ID,
		&i.CreatorID,
		&i.Title,
		&i.Description,
		&i.Location,
		&i.StartTime,
		&i.EndTime,
		&i.MaxPeople,
		&i.CurrentPeople,
		&i.Status,
		&i.AuditStatus,
		&i.CreatedAt,
		&i.IsEnrolled,
	)
	return i, err
}

const getActivityEnrollInfo = `-- name: GetActivityEnrollInfo :one
SELECT max_people, current_people, status
FROM activity
WHERE id = $1
`

type GetActivityEnrollInfoRow struct {
	MaxPeople     int32
	CurrentPeople int32
	Status        int16
}

func (q *Queries) GetActivityEnrollInfo(ctx context.Context, activityID int64) (GetActivityEnrollInfoRow, error) {
	row := q.db.QueryRow(ctx, getActivityEnrollInfo, activityID)
	var i GetActivityEnrollInfoRow
	err := row.Scan(&i.MaxPeople, &i.CurrentPeople, &i.Status)
	return i, err
}

const getCommentParent = `-- name: GetCommentParent :one
SELECT activity_id, user_id
FROM activity_comment
WHERE id = $1
`

type GetCommentParentRow struct {
	ActivityID int64
	UserID     int64
}

func (q *Queries) GetCommentParent(ctx context.Context, id int64) (GetCommentParentRow, error) {
	row := q.db.QueryRow(ctx, getCommentParent, id)
	var i GetCommentParentRow
	err := row.Scan(&i.ActivityID, &i.UserID)
	return i, err
}

const getEnrollmentStatus = `-- name: GetEnrollmentStatus :one
SELECT status
FROM enrollment
WHERE activity_id = $1
  AND user_id = $2
`

type GetEnrollmentStatusParams struct {
	ActivityID int64
	UserID     int64
}

func (q *Queries) GetEnrollmentStatus(ctx context.Context, arg GetEnrollmentStatusParams) (int16, error) {
	row := q.db.QueryRow(ctx, getEnrollmentStatus, arg.ActivityID, arg.UserID)
	var status int16
	err := row.Scan(&status)
	return status, err
}

const insertComment = `-- name: InsertComment :one
INSERT INTO activity_comment (activity_id, user_id, parent_id, content, audit_status, created_at)
VALUES ($1, $2, NULLIF($3, 0), $4, 0, now())
RETURNING id
`

type InsertCommentParams struct {
	ActivityID int64
	UserID     int64
	ParentID   interface{}
	Content    string
}

func (q *Queries) InsertComment(ctx context.Context, arg InsertCommentParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertComment,
		arg.ActivityID,
		arg.UserID,
		arg.ParentID,
		arg.Content,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertEnrollment = `-- name: InsertEnrollment :exec
INSERT INTO enrollment (activity_id, user_id, status, enroll_time)
VALUES ($1, $2, $3, $4)
`

type InsertEnrollmentParams struct {
	ActivityID int64
	UserID     int64
	Status     int16
	EnrollTime pgtype.Timestamptz
}

func (q *Queries) InsertEnrollment(ctx context.Context, arg InsertEnrollmentParams) error {
	_, err := q.db.Exec(ctx, insertEnrollment,
		arg.ActivityID,
		arg.UserID,
		arg.Status,
		arg.EnrollTime,
	)
	return err
}

const listActivities = `-- name: ListActivities :many
SELECT a.id,
       a.creator_id,
       a.title,
       a.description,
       a.location,
       a.start_time,
       a.end_time,
       a.max_people,
       a.current_people,
       a.status,
       a.audit_status,
       a.created_at,
       CASE WHEN e_viewer.id IS NULL THEN false ELSE true END AS is_enrolled
FROM activity a
LEFT JOIN enrollment e_filter ON e_filter.activity_id = a.id AND e_filter.user_id = $1 AND e_filter.status IN (1,2)
LEFT JOIN enrollment e_viewer ON e_viewer.activity_id = a.id AND e_viewer.user_id = $2 AND e_viewer.status IN (1,2)
WHERE (NOT $3 OR a.creator_id = $4)
  AND (NOT $5 OR e_filter.id IS NOT NULL)
  AND ($6 = -1 OR a.status = $6)
  AND ($7 = -1 OR a.audit_status = $7)
  AND ($8 = '' OR a.title ILIKE '%' || $8 || '%' OR a.description ILIKE '%' || $8 || '%')
ORDER BY a.start_time DESC
LIMIT $10 OFFSET $9
`

type ListActivitiesParams struct {
	EnrolledUserID int64
	ViewerUserID   int64
	UseCreator     interface{}
	CreatorID      int64
	UseEnrolled    interface{}
	Status         interface{}
	AuditStatus    interface{}
	Keyword        interface{}
	PageOffset     int32
	PageLimit      int32
}

type ListActivitiesRow struct {
	ID            int64
	CreatorID     int64
	Title         string
	Description   pgtype.Text
	Location      string
	StartTime     pgtype.Timestamptz
	EndTime       pgtype.Timestamptz
	MaxPeople     int32
	CurrentPeople int32
	Status        int16
	AuditStatus   int16
	CreatedAt     pgtype.Timestamptz
	IsEnrolled    bool
}

func (q *Queries) ListActivities(ctx context.Context, arg ListActivitiesParams) ([]ListActivitiesRow, error) {
	rows, err := q.db.Query(ctx, listActivities,
		arg.EnrolledUserID,
		arg.ViewerUserID,
		arg.UseCreator,
		arg.CreatorID,
		arg.UseEnrolled,
		arg.Status,
		arg.AuditStatus,
		arg.Keyword,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActivitiesRow{}
	for rows.Next() {
		var i ListActivitiesRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatorID,
			&i.Title,
			&i.Description,
			&i.Location,
			&i.StartTime,
			&i.EndTime,
			&i.MaxPeople,
			&i.CurrentPeople,
			&i.Status,
			&i.AuditStatus,
			&i.CreatedAt,
			&i.IsEnrolled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listComments = `-- name: ListComments :many
SELECT id, activity_id, user_id, COALESCE(parent_id, 0) AS parent_id, content, audit_status, created_at
FROM activity_comment
WHERE activity_id = $1
  AND (
    ($2 = 0 AND parent_id IS NULL)
    OR
    ($2 <> 0 AND parent_id = $2)
  )
  AND ($3 OR audit_status = 1)
ORDER BY created_at DESC
LIMIT $5 OFFSET $4
`

type ListCommentsParams struct {
	ActivityID        int64
	ParentID          interface{}
	IncludeUnapproved interface{}
	PageOffset        int32
	PageLimit         int32
}

type ListCommentsRow struct {
	ID          int64
	ActivityID  int64
	UserID      int64
	ParentID    int64
	Content     string
	AuditStatus int16
	CreatedAt   pgtype.Timestamptz
}

func (q *Queries) ListComments(ctx context.Context, arg ListCommentsParams) ([]ListCommentsRow, error) {
	rows, err := q.db.Query(ctx, listComments,
		arg.ActivityID,
		arg.ParentID,
		arg.IncludeUnapproved,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCommentsRow{}
	for rows.Next() {
		var i ListCommentsRow
		if err := rows.Scan(
			&i.ID,
			&i.ActivityID,
			&i.UserID,
			&i.ParentID,
			&i.Content,
			&i.AuditStatus,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listParticipants = `-- name: ListParticipants :many
SELECT user_id, enroll_time, checkin_time, status
FROM enrollment
WHERE activity_id = $1
  AND status IN (1,2)
ORDER BY enroll_time DESC
LIMIT $3 OFFSET $2
`

type ListParticipantsParams struct {
	ActivityID int64
	PageOffset int32
	PageLimit  int32
}

type ListParticipantsRow struct {
	UserID      int64
	EnrollTime  pgtype.Timestamptz
	CheckinTime pgtype.Timestamptz
	Status      int16
}

func (q *Queries) ListParticipants(ctx context.Context, arg ListParticipantsParams) ([]ListParticipantsRow, error) {
	rows, err := q.db.Query(ctx, listParticipants, arg.ActivityID, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListParticipantsRow{}
	for rows.Next() {
		var i ListParticipantsRow
		if err := rows.Scan(
			&i.UserID,
			&i.EnrollTime,
			&i.CheckinTime,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateActivity = `-- name: UpdateActivity :execrows
UPDATE activity
SET title = COALESCE(NULLIF($1, ''), title),
    description = COALESCE(NULLIF($2, ''), description),
    location = COALESCE(NULLIF($3, ''), location),
    start_time = COALESCE($4, start_time),
    end_time = COALESCE($5, end_time),
    max_people = COALESCE(NULLIF($6, -1), max_people),
    status = COALESCE(NULLIF($7, -1), status),
    audit_status = 0,
    updated_at = now()
WHERE id = $8 AND creator_id = $9
`

type UpdateActivityParams struct {
	Title       interface{}
	Description interface{}
	Location    interface{}
	StartTime   pgtype.Timestamptz
	EndTime     pgtype.Timestamptz
	MaxPeople   interface{}
	Status      interface{}
	ID          int64
	CreatorID   int64
}

func (q *Queries) UpdateActivity(ctx context.Context, arg UpdateActivityParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateActivity,
		arg.Title,
		arg.Description,
		arg.Location,
		arg.StartTime,
		arg.EndTime,
		arg.MaxPeople,
		arg.Status,
		arg.ID,
		arg.CreatorID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateActivityAuditStatus = `-- name: UpdateActivityAuditStatus :execrows
UPDATE activity
SET audit_status = $1,
    updated_at = now()
WHERE id = $2
`

type UpdateActivityAuditStatusParams struct {
	AuditStatus int16
	ID          int64
}

func (q *Queries) UpdateActivityAuditStatus(ctx context.Context, arg UpdateActivityAuditStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateActivityAuditStatus, arg.AuditStatus, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateActivityPeople = `-- name: UpdateActivityPeople :exec
UPDATE activity
SET current_people = GREATEST(current_people + $1, 0)
WHERE id = $2
`

type UpdateActivityPeopleParams struct {
	Delta      int32
	ActivityID int64
}

func (q *Queries) UpdateActivityPeople(ctx context.Context, arg UpdateActivityPeopleParams) error {
	_, err := q.db.Exec(ctx, updateActivityPeople, arg.Delta, arg.ActivityID)
	return err
}

const updateCommentAuditStatus = `-- name: UpdateCommentAuditStatus :execrows
UPDATE activity_comment
SET audit_status = $1
WHERE id = $2
`

type UpdateCommentAuditStatusParams struct {
	AuditStatus int16
	ID          int64
}

func (q *Queries) UpdateCommentAuditStatus(ctx context.Context, arg UpdateCommentAuditStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateCommentAuditStatus, arg.AuditStatus, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateEnrollmentStatus = `-- name: UpdateEnrollmentStatus :exec
UPDATE enrollment
SET status = $1
WHERE activity_id = $2
  AND user_id = $3
`

type UpdateEnrollmentStatusParams struct {
	Status     int16
	ActivityID int64
	UserID     int64
}

func (q *Queries) UpdateEnrollmentStatus(ctx context.Context, arg UpdateEnrollmentStatusParams) error {
	_, err := q.db.Exec(ctx, updateEnrollmentStatus, arg.Status, arg.ActivityID, arg.UserID)
	return err
}

const updateEnrollmentStatusWithCheckinTime = `-- name: UpdateEnrollmentStatusWithCheckinTime :exec
UPDATE enrollment
SET status = $1,
    checkin_time = $2
WHERE activity_id = $3
  AND user_id = $4
`

type UpdateEnrollmentStatusWithCheckinTimeParams struct {
	Status      int16
	CheckinTime pgtype.Timestamptz
	ActivityID  int64
	UserID      int64
}

func (q *Queries) UpdateEnrollmentStatusWithCheckinTime(ctx context.Context, arg UpdateEnrollmentStatusWithCheckinTimeParams) error {
	_, err := q.db.Exec(ctx, updateEnrollmentStatusWithCheckinTime,
		arg.Status,
		arg.CheckinTime,
		arg.ActivityID,
		arg.UserID,
	)
	return err
}

const updateEnrollmentStatusWithEnrollTime = `-- name: UpdateEnrollmentStatusWithEnrollTime :exec
UPDATE enrollment
SET status = $1,
    enroll_time = $2
WHERE activity_id = $3
  AND user_id = $4
`

type UpdateEnrollmentStatusWithEnrollTimeParams struct {
	Status     int16
	EnrollTime pgtype.Timestamptz
	ActivityID int64
	UserID     int64
}

func (q *Queries) UpdateEnrollmentStatusWithEnrollTime(ctx context.Context, arg UpdateEnrollmentStatusWithEnrollTimeParams) error {
	_, err := q.db.Exec(ctx, updateEnrollmentStatusWithEnrollTime,
		arg.Status,
		arg.EnrollTime,
		arg.ActivityID,
		arg.UserID,
	)
	return err
}
