// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type GetUserInfoRequest struct {
}

type LoginRequest struct {
	Mobile   string `json:"mobile"`
	Password string `json:"password"`
}

type LoginResponse struct {
	UserId   uint64   `json:"user_id"`
	Token    string   `json:"token"`
	UserInfo UserInfo `json:"user_info"`
}

type RegisterRequest struct {
	Mobile     string `json:"mobile"`
	Password   string `json:"password"`
	Nickname   string `json:"nickname"`
	VerifyCode string `json:"verify_code"`
}

type RegisterResponse struct {
	UserId uint64 `json:"user_id"`
	Token  string `json:"token"`
}

type UserInfo struct {
	Id       uint64 `json:"id"`
	Mobile   string `json:"mobile"`
	Nickname string `json:"nickname"`
	Avatar   string `json:"avatar"`
}
