// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package sqlc

import (
	"context"
)

const getLoginInfo = `-- name: GetLoginInfo :one
SELECT id, password_hash, nickname, avatar
FROM "user"
WHERE mobile = $1
`

type GetLoginInfoRow struct {
	ID           int64
	PasswordHash string
	Nickname     string
	Avatar       string
}

func (q *Queries) GetLoginInfo(ctx context.Context, mobile string) (GetLoginInfoRow, error) {
	row := q.db.QueryRow(ctx, getLoginInfo, mobile)
	var i GetLoginInfoRow
	err := row.Scan(
		&i.ID,
		&i.PasswordHash,
		&i.Nickname,
		&i.Avatar,
	)
	return i, err
}

const getUserIDByMobile = `-- name: GetUserIDByMobile :one
SELECT id FROM "user" WHERE mobile = $1
`

func (q *Queries) GetUserIDByMobile(ctx context.Context, mobile string) (int64, error) {
	row := q.db.QueryRow(ctx, getUserIDByMobile, mobile)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getUserInfo = `-- name: GetUserInfo :one
SELECT id, mobile, nickname, avatar, audit_status
FROM "user"
WHERE id = $1
`

type GetUserInfoRow struct {
	ID          int64
	Mobile      string
	Nickname    string
	Avatar      string
	AuditStatus int16
}

func (q *Queries) GetUserInfo(ctx context.Context, id int64) (GetUserInfoRow, error) {
	row := q.db.QueryRow(ctx, getUserInfo, id)
	var i GetUserInfoRow
	err := row.Scan(
		&i.ID,
		&i.Mobile,
		&i.Nickname,
		&i.Avatar,
		&i.AuditStatus,
	)
	return i, err
}

const insertUser = `-- name: InsertUser :one
INSERT INTO "user" (mobile, password_hash, nickname, avatar)
VALUES ($1, $2, $3, $4)
RETURNING id
`

type InsertUserParams struct {
	Mobile       string
	PasswordHash string
	Nickname     string
	Avatar       string
}

func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertUser,
		arg.Mobile,
		arg.PasswordHash,
		arg.Nickname,
		arg.Avatar,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const updateUserAuditStatus = `-- name: UpdateUserAuditStatus :execrows
UPDATE "user"
SET audit_status = $1,
    updated_at = now()
WHERE id = $2
`

type UpdateUserAuditStatusParams struct {
	AuditStatus int16
	ID          int64
}

func (q *Queries) UpdateUserAuditStatus(ctx context.Context, arg UpdateUserAuditStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateUserAuditStatus, arg.AuditStatus, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateUserInfo = `-- name: UpdateUserInfo :execrows
UPDATE "user"
SET nickname = COALESCE(NULLIF($1, ''), nickname),
    avatar = COALESCE(NULLIF($2, ''), avatar),
    audit_status = 0,
    updated_at = now()
WHERE id = $3
`

type UpdateUserInfoParams struct {
	Nickname interface{}
	Avatar   interface{}
	ID       int64
}

func (q *Queries) UpdateUserInfo(ctx context.Context, arg UpdateUserInfoParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateUserInfo, arg.Nickname, arg.Avatar, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
