// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.4
// source: activity/activity.proto

package activity

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ActivityInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatorId     uint64                 `protobuf:"varint,2,opt,name=creator_id,json=creatorId,proto3" json:"creator_id,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Location      string                 `protobuf:"bytes,5,opt,name=location,proto3" json:"location,omitempty"`
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	MaxPeople     int32                  `protobuf:"varint,8,opt,name=max_people,json=maxPeople,proto3" json:"max_people,omitempty"`
	CurrentPeople int32                  `protobuf:"varint,9,opt,name=current_people,json=currentPeople,proto3" json:"current_people,omitempty"`
	Status        int32                  `protobuf:"varint,10,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	CreatorName   string                 `protobuf:"bytes,12,opt,name=creator_name,json=creatorName,proto3" json:"creator_name,omitempty"`
	CreatorAvatar string                 `protobuf:"bytes,13,opt,name=creator_avatar,json=creatorAvatar,proto3" json:"creator_avatar,omitempty"`
	IsEnrolled    bool                   `protobuf:"varint,14,opt,name=is_enrolled,json=isEnrolled,proto3" json:"is_enrolled,omitempty"`
	AuditStatus   int32                  `protobuf:"varint,15,opt,name=audit_status,json=auditStatus,proto3" json:"audit_status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivityInfo) Reset() {
	*x = ActivityInfo{}
	mi := &file_activity_activity_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivityInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivityInfo) ProtoMessage() {}

func (x *ActivityInfo) ProtoReflect() protoreflect.Message {
	mi := &file_activity_activity_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivityInfo.ProtoReflect.Descriptor instead.
func (*ActivityInfo) Descriptor() ([]byte, []int) {
	return file_activity_activity_proto_rawDescGZIP(), []int{0}
}

func (x *ActivityInfo) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ActivityInfo) GetCreatorId() uint64 {
	if x != nil {
		return x.CreatorId
	}
	return 0
}

func (x *ActivityInfo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ActivityInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ActivityInfo) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *ActivityInfo) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *ActivityInfo) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *ActivityInfo) GetMaxPeople() int32 {
	if x != nil {
		return x.MaxPeople
	}
	return 0
}

func (x *ActivityInfo) GetCurrentPeople() int32 {
	if x != nil {
		return x.CurrentPeople
	}
	return 0
}

func (x *ActivityInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ActivityInfo) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ActivityInfo) GetCreatorName() string {
	if x != nil {
		return x.CreatorName
	}
	return ""
}

func (x *ActivityInfo) GetCreatorAvatar() string {
	if x != nil {
		return x.CreatorAvatar
	}
	return ""
}

func (x *ActivityInfo) GetIsEnrolled() bool {
	if x != nil {
		return x.IsEnrolled
	}
	return false
}

func (x *ActivityInfo) GetAuditStatus() int32 {
	if x != nil {
		return x.AuditStatus
	}
	return 0
}

type CreateActivityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CreatorId     uint64                 `protobuf:"varint,1,opt,name=creator_id,json=creatorId,proto3" json:"creator_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Location      string                 `protobuf:"bytes,4,opt,name=location,proto3" json:"location,omitempty"`
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	MaxPeople     int32                  `protobuf:"varint,7,opt,name=max_people,json=maxPeople,proto3" json:"max_people,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateActivityRequest) Reset() {
	*x = CreateActivityRequest{}
	mi := &file_activity_activity_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateActivityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateActivityRequest) ProtoMessage() {}

func (x *CreateActivityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_activity_activity_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateActivityRequest.ProtoReflect.Descriptor instead.
func (*CreateActivityRequest) Descriptor() ([]byte, []int) {
	return file_activity_activity_proto_rawDescGZIP(), []int{1}
}

func (x *CreateActivityRequest) GetCreatorId() uint64 {
	if x != nil {
		return x.CreatorId
	}
	return 0
}

func (x *CreateActivityRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateActivityRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateActivityRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *CreateActivityRequest) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *CreateActivityRequest) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *CreateActivityRequest) GetMaxPeople() int32 {
	if x != nil {
		return x.MaxPeople
	}
	return 0
}

type GetActivityListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Status        int32                  `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	Keyword       string                 `protobuf:"bytes,4,opt,name=keyword,proto3" json:"keyword,omitempty"`
	ViewerUserId  uint64                 `protobuf:"varint,5,opt,name=viewer_user_id,json=viewerUserId,proto3" json:"viewer_user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetActivityListRequest) Reset() {
	*x = GetActivityListRequest{}
	mi := &file_activity_activity_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetActivityListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActivityListRequest) ProtoMessage() {}

func (x *GetActivityListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_activity_activity_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActivityListRequest.ProtoReflect.Descriptor instead.
func (*GetActivityListRequest) Descriptor() ([]byte, []int) {
	return file_activity_activity_proto_rawDescGZIP(), []int{2}
}

func (x *GetActivityListRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetActivityListRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *GetActivityListRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *GetActivityListRequest) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *GetActivityListRequest) GetViewerUserId() uint64 {
	if x != nil {
		return x.ViewerUserId
	}
	return 0
}

type GetActivityListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Activities    []*ActivityInfo        `protobuf:"bytes,1,rep,name=activities,proto3" json:"activities,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetActivityListResponse) Reset() {
	*x = GetActivityListResponse{}
	mi := &file_activity_activity_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetActivityListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActivityListResponse) ProtoMessage() {}

func (x *GetActivityListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_activity_activity_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActivityListResponse.ProtoReflect.Descriptor instead.
func (*GetActivityListResponse) Descriptor() ([]byte, []int) {
	return file_activity_activity_proto_rawDescGZIP(), []int{3}
}

func (x *GetActivityListResponse) GetActivities() []*ActivityInfo {
	if x != nil {
		return x.Activities
	}
	return nil
}

func (x *GetActivityListResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type GetActivityDetailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ViewerUserId  uint64                 `protobuf:"varint,2,opt,name=viewer_user_id,json=viewerUserId,proto3" json:"viewer_user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetActivityDetailRequest) Reset() {
	*x = GetActivityDetailRequest{}
	mi := &file_activity_activity_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetActivityDetailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActivityDetailRequest) ProtoMessage() {}

func (x *GetActivityDetailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_activity_activity_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActivityDetailRequest.ProtoReflect.Descriptor instead.
func (*GetActivityDetailRequest) Descriptor() ([]byte, []int) {
	return file_activity_activity_proto_rawDescGZIP(), []int{4}
}

func (x *GetActivityDetailRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetActivityDetailRequest) GetViewerUserId() uint64 {
	if x != nil {
		return x.ViewerUserId
	}
	return 0
}

type EnrollActivityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActivityId    uint64                 `protobuf:"varint,1,opt,name=activity_id,json=activityId,proto3" json:"activity_id,omitempty"`
	UserId        uint64                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrollActivityRequest) Reset() {
	*x = EnrollActivityRequest{}
	mi := &file_activity_activity_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollActivityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollActivityRequest) ProtoMessage() {}

func (x *EnrollActivityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_activity_activity_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollActivityRequest.ProtoReflect.Descriptor instead.
func (*EnrollActivityRequest) Descriptor() ([]byte, []int) {
	return file_activity_activity_proto_rawDescGZIP(), []int{5}
}

func (x *EnrollActivityRequest) GetActivityId() uint64 {
	if x != nil {
		return x.ActivityId
	}
	return 0
}

func (x *EnrollActivityRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type EnrollActivityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrollActivityResponse) Reset() {
	*x = EnrollActivityResponse{}
	mi := &file_activity_activity_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollActivityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollActivityResponse) ProtoMessage() {}

func (x *EnrollActivityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_activity_activity_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollActivityResponse.ProtoReflect.Descriptor instead.
func (*EnrollActivityResponse) Descriptor() ([]byte, []int) {
	return file_activity_activity_proto_rawDescGZIP(), []int{6}
}

func (x *EnrollActivityResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *EnrollActivityResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type CancelEnrollRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActivityId    uint64                 `protobuf:"varint,1,opt,name=activity_id,json=activityId,proto3" json:"activity_id,omitempty"`
	UserId        uint64                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelEnrollRequest) Reset() {
	*x = CancelEnrollRequest{}
	mi := &file_activity_activity_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelEnrollRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelEnrollRequest) ProtoMessage() {}

func (x *CancelEnrollRequest) ProtoReflect() protoreflect.Message {
	mi := &file_activity_activity_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelEnrollRequest.ProtoReflect.Descriptor instead.
func (*CancelEnrollRequest) Descriptor() ([]byte, []int) {
	return file_activity_activity_proto_rawDescGZIP(), []int{7}
}

func (x *CancelEnrollRequest) GetActivityId() uint64 {
	if x != nil {
		return x.ActivityId
	}
	return 0
}

func (x *CancelEnrollRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type CheckInRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActivityId    uint64                 `protobuf:"varint,1,opt,name=activity_id,json=activityId,proto3" json:"activity_id,omitempty"`
	UserId        uint64                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Code          string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckInRequest) Reset() {
	*x = CheckInRequest{}
	mi := &file_activity_activity_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckInRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckInRequest) ProtoMessage() {}

func (x *CheckInRequest) ProtoReflect() protoreflect.Message {
	mi := &file_activity_activity_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckInRequest.ProtoReflect.Descriptor instead.
func (*CheckInRequest) Descriptor() ([]byte, []int) {
	return file_activity_activity_proto_rawDescGZIP(), []int{8}
}

func (x *CheckInRequest) GetActivityId() uint64 {
	if x != nil {
		return x.ActivityId
	}
	return 0
}

func (x *CheckInRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CheckInRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type UpdateActivityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatorId     uint64                 `protobuf:"varint,2,opt,name=creator_id,json=creatorId,proto3" json:"creator_id,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Location      string                 `protobuf:"bytes,5,opt,name=location,proto3" json:"location,omitempty"`
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	MaxPeople     int32                  `protobuf:"varint,8,opt,name=max_people,json=maxPeople,proto3" json:"max_people,omitempty"`
	Status        int32                  `protobuf:"varint,9,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateActivityRequest) Reset() {
	*x = UpdateActivityRequest{}
	mi := &file_activity_activity_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateActivityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateActivityRequest) ProtoMessage() {}

func (x *UpdateActivityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_activity_activity_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateActivityRequest.ProtoReflect.Descriptor instead.
func (*UpdateActivityRequest) Descriptor() ([]byte, []int) {
	return file_activity_activity_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateActivityRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateActivityRequest) GetCreatorId() uint64 {
	if x != nil {
		return x.CreatorId
	}
	return 0
}

func (x *UpdateActivityRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateActivityRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateActivityRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *UpdateActivityRequest) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *UpdateActivityRequest) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *UpdateActivityRequest) GetMaxPeople() int32 {
	if x != nil {
		return x.MaxPeople
	}
	return 0
}

func (x *UpdateActivityRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type UpdateAuditStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActivityId    uint64                 `protobuf:"varint,1,opt,name=activity_id,json=activityId,proto3" json:"activity_id,omitempty"`
	AuditStatus   int32                  `protobuf:"varint,2,opt,name=audit_status,json=auditStatus,proto3" json:"audit_status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAuditStatusRequest) Reset() {
	*x = UpdateAuditStatusRequest{}
	mi := &file_activity_activity_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAuditStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAuditStatusRequest) ProtoMessage() {}

func (x *UpdateAuditStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_activity_activity_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAuditStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateAuditStatusRequest) Descriptor() ([]byte, []int) {
	return file_activity_activity_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateAuditStatusRequest) GetActivityId() uint64 {
	if x != nil {
		return x.ActivityId
	}
	return 0
}

func (x *UpdateAuditStatusRequest) GetAuditStatus() int32 {
	if x != nil {
		return x.AuditStatus
	}
	return 0
}

type UpdateAuditStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAuditStatusResponse) Reset() {
	*x = UpdateAuditStatusResponse{}
	mi := &file_activity_activity_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAuditStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAuditStatusResponse) ProtoMessage() {}

func (x *UpdateAuditStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_activity_activity_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAuditStatusResponse.ProtoReflect.Descriptor instead.
func (*UpdateAuditStatusResponse) Descriptor() ([]byte, []int) {
	return file_activity_activity_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateAuditStatusResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateAuditStatusResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type CommentInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ActivityId    uint64                 `protobuf:"varint,2,opt,name=activity_id,json=activityId,proto3" json:"activity_id,omitempty"`
	UserId        uint64                 `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ParentId      uint64                 `protobuf:"varint,4,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	Content       string                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	AuditStatus   int32                  `protobuf:"varint,7,opt,name=audit_status,json=auditStatus,proto3" json:"audit_status,omitempty"`
	Nickname      string                 `protobuf:"bytes,8,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Avatar        string                 `protobuf:"bytes,9,opt,name=avatar,proto3" json:"avatar,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommentInfo) Reset() {
	*x = CommentInfo{}
	mi := &file_activity_activity_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommentInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommentInfo) ProtoMessage() {}

func (x *CommentInfo) ProtoReflect() protoreflect.Message {
	mi := &file_activity_activity_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommentInfo.ProtoReflect.Descriptor instead.
func (*CommentInfo) Descriptor() ([]byte, []int) {
	return file_activity_activity_proto_rawDescGZIP(), []int{12}
}

func (x *CommentInfo) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CommentInfo) GetActivityId() uint64 {
	if x != nil {
		return x.ActivityId
	}
	return 0
}

func (x *CommentInfo) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CommentInfo) GetParentId() uint64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *CommentInfo) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CommentInfo) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *CommentInfo) GetAuditStatus() int32 {
	if x != nil {
		return x.AuditStatus
	}
	return 0
}

func (x *CommentInfo) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *CommentInfo) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

type CreateCommentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActivityId    uint64                 `protobuf:"varint,1,opt,name=activity_id,json=activityId,proto3" json:"activity_id,omitempty"`
	UserId        uint64                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	ParentId      uint64                 `protobuf:"varint,4,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCommentRequest) Reset() {
	*x = CreateCommentRequest{}
	mi := &file_activity_activity_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCommentRequest) ProtoMessage() {}

func (x *CreateCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_activity_activity_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCommentRequest.ProtoReflect.Descriptor instead.
func (*CreateCommentRequest) Descriptor() ([]byte, []int) {
	return file_activity_activity_proto_rawDescGZIP(), []int{13}
}

func (x *CreateCommentRequest) GetActivityId() uint64 {
	if x != nil {
		return x.ActivityId
	}
	return 0
}

func (x *CreateCommentRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateCommentRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CreateCommentRequest) GetParentId() uint64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

type CreateCommentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommentId     uint64                 `protobuf:"varint,1,opt,name=comment_id,json=commentId,proto3" json:"comment_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCommentResponse) Reset() {
	*x = CreateCommentResponse{}
	mi := &file_activity_activity_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCommentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCommentResponse) ProtoMessage() {}

func (x *CreateCommentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_activity_activity_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCommentResponse.ProtoReflect.Descriptor instead.
func (*CreateCommentResponse) Descriptor() ([]byte, []int) {
	return file_activity_activity_proto_rawDescGZIP(), []int{14}
}

func (x *CreateCommentResponse) GetCommentId() uint64 {
	if x != nil {
		return x.CommentId
	}
	return 0
}

type GetCommentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActivityId    uint64                 `protobuf:"varint,1,opt,name=activity_id,json=activityId,proto3" json:"activity_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	ViewerUserId  uint64                 `protobuf:"varint,4,opt,name=viewer_user_id,json=viewerUserId,proto3" json:"viewer_user_id,omitempty"`
	ParentId      uint64                 `protobuf:"varint,5,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCommentsRequest) Reset() {
	*x = GetCommentsRequest{}
	mi := &file_activity_activity_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCommentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommentsRequest) ProtoMessage() {}

func (x *GetCommentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_activity_activity_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommentsRequest.ProtoReflect.Descriptor instead.
func (*GetCommentsRequest) Descriptor() ([]byte, []int) {
	return file_activity_activity_proto_rawDescGZIP(), []int{15}
}

func (x *GetCommentsRequest) GetActivityId() uint64 {
	if x != nil {
		return x.ActivityId
	}
	return 0
}

func (x *GetCommentsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetCommentsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *GetCommentsRequest) GetViewerUserId() uint64 {
	if x != nil {
		return x.ViewerUserId
	}
	return 0
}

func (x *GetCommentsRequest) GetParentId() uint64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

type GetCommentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Comments      []*CommentInfo         `protobuf:"bytes,1,rep,name=comments,proto3" json:"comments,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCommentsResponse) Reset() {
	*x = GetCommentsResponse{}
	mi := &file_activity_activity_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCommentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommentsResponse) ProtoMessage() {}

func (x *GetCommentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_activity_activity_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommentsResponse.ProtoReflect.Descriptor instead.
func (*GetCommentsResponse) Descriptor() ([]byte, []int) {
	return file_activity_activity_proto_rawDescGZIP(), []int{16}
}

func (x *GetCommentsResponse) GetComments() []*CommentInfo {
	if x != nil {
		return x.Comments
	}
	return nil
}

func (x *GetCommentsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type UpdateCommentAuditStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommentId     uint64                 `protobuf:"varint,1,opt,name=comment_id,json=commentId,proto3" json:"comment_id,omitempty"`
	AuditStatus   int32                  `protobuf:"varint,2,opt,name=audit_status,json=auditStatus,proto3" json:"audit_status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCommentAuditStatusRequest) Reset() {
	*x = UpdateCommentAuditStatusRequest{}
	mi := &file_activity_activity_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCommentAuditStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCommentAuditStatusRequest) ProtoMessage() {}

func (x *UpdateCommentAuditStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_activity_activity_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCommentAuditStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateCommentAuditStatusRequest) Descriptor() ([]byte, []int) {
	return file_activity_activity_proto_rawDescGZIP(), []int{17}
}

func (x *UpdateCommentAuditStatusRequest) GetCommentId() uint64 {
	if x != nil {
		return x.CommentId
	}
	return 0
}

func (x *UpdateCommentAuditStatusRequest) GetAuditStatus() int32 {
	if x != nil {
		return x.AuditStatus
	}
	return 0
}

type UpdateCommentAuditStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCommentAuditStatusResponse) Reset() {
	*x = UpdateCommentAuditStatusResponse{}
	mi := &file_activity_activity_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCommentAuditStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCommentAuditStatusResponse) ProtoMessage() {}

func (x *UpdateCommentAuditStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_activity_activity_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCommentAuditStatusResponse.ProtoReflect.Descriptor instead.
func (*UpdateCommentAuditStatusResponse) Descriptor() ([]byte, []int) {
	return file_activity_activity_proto_rawDescGZIP(), []int{18}
}

func (x *UpdateCommentAuditStatusResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateCommentAuditStatusResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetMyActivitiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMyActivitiesRequest) Reset() {
	*x = GetMyActivitiesRequest{}
	mi := &file_activity_activity_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMyActivitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMyActivitiesRequest) ProtoMessage() {}

func (x *GetMyActivitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_activity_activity_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMyActivitiesRequest.ProtoReflect.Descriptor instead.
func (*GetMyActivitiesRequest) Descriptor() ([]byte, []int) {
	return file_activity_activity_proto_rawDescGZIP(), []int{19}
}

func (x *GetMyActivitiesRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetMyActivitiesRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetMyActivitiesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type GetEnrolledActivitiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEnrolledActivitiesRequest) Reset() {
	*x = GetEnrolledActivitiesRequest{}
	mi := &file_activity_activity_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEnrolledActivitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEnrolledActivitiesRequest) ProtoMessage() {}

func (x *GetEnrolledActivitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_activity_activity_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEnrolledActivitiesRequest.ProtoReflect.Descriptor instead.
func (*GetEnrolledActivitiesRequest) Descriptor() ([]byte, []int) {
	return file_activity_activity_proto_rawDescGZIP(), []int{20}
}

func (x *GetEnrolledActivitiesRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetEnrolledActivitiesRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetEnrolledActivitiesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ParticipantInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Nickname      string                 `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Avatar        string                 `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`
	EnrollTime    *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=enroll_time,json=enrollTime,proto3" json:"enroll_time,omitempty"`
	CheckinTime   *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=checkin_time,json=checkinTime,proto3" json:"checkin_time,omitempty"`
	Status        int32                  `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParticipantInfo) Reset() {
	*x = ParticipantInfo{}
	mi := &file_activity_activity_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParticipantInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParticipantInfo) ProtoMessage() {}

func (x *ParticipantInfo) ProtoReflect() protoreflect.Message {
	mi := &file_activity_activity_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParticipantInfo.ProtoReflect.Descriptor instead.
func (*ParticipantInfo) Descriptor() ([]byte, []int) {
	return file_activity_activity_proto_rawDescGZIP(), []int{21}
}

func (x *ParticipantInfo) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ParticipantInfo) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *ParticipantInfo) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *ParticipantInfo) GetEnrollTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EnrollTime
	}
	return nil
}

func (x *ParticipantInfo) GetCheckinTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CheckinTime
	}
	return nil
}

func (x *ParticipantInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type GetParticipantsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActivityId    uint64                 `protobuf:"varint,1,opt,name=activity_id,json=activityId,proto3" json:"activity_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetParticipantsRequest) Reset() {
	*x = GetParticipantsRequest{}
	mi := &file_activity_activity_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetParticipantsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetParticipantsRequest) ProtoMessage() {}

func (x *GetParticipantsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_activity_activity_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetParticipantsRequest.ProtoReflect.Descriptor instead.
func (*GetParticipantsRequest) Descriptor() ([]byte, []int) {
	return file_activity_activity_proto_rawDescGZIP(), []int{22}
}

func (x *GetParticipantsRequest) GetActivityId() uint64 {
	if x != nil {
		return x.ActivityId
	}
	return 0
}

func (x *GetParticipantsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetParticipantsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type GetParticipantsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Participants  []*ParticipantInfo     `protobuf:"bytes,1,rep,name=participants,proto3" json:"participants,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetParticipantsResponse) Reset() {
	*x = GetParticipantsResponse{}
	mi := &file_activity_activity_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetParticipantsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetParticipantsResponse) ProtoMessage() {}

func (x *GetParticipantsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_activity_activity_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetParticipantsResponse.ProtoReflect.Descriptor instead.
func (*GetParticipantsResponse) Descriptor() ([]byte, []int) {
	return file_activity_activity_proto_rawDescGZIP(), []int{23}
}

func (x *GetParticipantsResponse) GetParticipants() []*ParticipantInfo {
	if x != nil {
		return x.Participants
	}
	return nil
}

func (x *GetParticipantsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_activity_activity_proto protoreflect.FileDescriptor

const file_activity_activity_proto_rawDesc = "" +
	"\n" +
	"\x17activity/activity.proto\x12\bactivity\x1a\x1fgoogle/protobuf/timestamp.proto\"\xaa\x04\n" +
	"\fActivityInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x1d\n" +
	"\n" +
	"creator_id\x18\x02 \x01(\x04R\tcreatorId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1a\n" +
	"\blocation\x18\x05 \x01(\tR\blocation\x129\n" +
	"\n" +
	"start_time\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\x12\x1d\n" +
	"\n" +
	"max_people\x18\b \x01(\x05R\tmaxPeople\x12%\n" +
	"\x0ecurrent_people\x18\t \x01(\x05R\rcurrentPeople\x12\x16\n" +
	"\x06status\x18\n" +
	" \x01(\x05R\x06status\x129\n" +
	"\n" +
	"created_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12!\n" +
	"\fcreator_name\x18\f \x01(\tR\vcreatorName\x12%\n" +
	"\x0ecreator_avatar\x18\r \x01(\tR\rcreatorAvatar\x12\x1f\n" +
	"\vis_enrolled\x18\x0e \x01(\bR\n" +
	"isEnrolled\x12!\n" +
	"\faudit_status\x18\x0f \x01(\x05R\vauditStatus\"\x9b\x02\n" +
	"\x15CreateActivityRequest\x12\x1d\n" +
	"\n" +
	"creator_id\x18\x01 \x01(\x04R\tcreatorId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1a\n" +
	"\blocation\x18\x04 \x01(\tR\blocation\x129\n" +
	"\n" +
	"start_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\x12\x1d\n" +
	"\n" +
	"max_people\x18\a \x01(\x05R\tmaxPeople\"\xa1\x01\n" +
	"\x16GetActivityListRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x16\n" +
	"\x06status\x18\x03 \x01(\x05R\x06status\x12\x18\n" +
	"\akeyword\x18\x04 \x01(\tR\akeyword\x12$\n" +
	"\x0eviewer_user_id\x18\x05 \x01(\x04R\fviewerUserId\"g\n" +
	"\x17GetActivityListResponse\x126\n" +
	"\n" +
	"activities\x18\x01 \x03(\v2\x16.activity.ActivityInfoR\n" +
	"activities\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"P\n" +
	"\x18GetActivityDetailRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12$\n" +
	"\x0eviewer_user_id\x18\x02 \x01(\x04R\fviewerUserId\"Q\n" +
	"\x15EnrollActivityRequest\x12\x1f\n" +
	"\vactivity_id\x18\x01 \x01(\x04R\n" +
	"activityId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x04R\x06userId\"L\n" +
	"\x16EnrollActivityResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"O\n" +
	"\x13CancelEnrollRequest\x12\x1f\n" +
	"\vactivity_id\x18\x01 \x01(\x04R\n" +
	"activityId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x04R\x06userId\"^\n" +
	"\x0eCheckInRequest\x12\x1f\n" +
	"\vactivity_id\x18\x01 \x01(\x04R\n" +
	"activityId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x04R\x06userId\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\"\xc3\x02\n" +
	"\x15UpdateActivityRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x1d\n" +
	"\n" +
	"creator_id\x18\x02 \x01(\x04R\tcreatorId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1a\n" +
	"\blocation\x18\x05 \x01(\tR\blocation\x129\n" +
	"\n" +
	"start_time\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\x12\x1d\n" +
	"\n" +
	"max_people\x18\b \x01(\x05R\tmaxPeople\x12\x16\n" +
	"\x06status\x18\t \x01(\x05R\x06status\"^\n" +
	"\x18UpdateAuditStatusRequest\x12\x1f\n" +
	"\vactivity_id\x18\x01 \x01(\x04R\n" +
	"activityId\x12!\n" +
	"\faudit_status\x18\x02 \x01(\x05R\vauditStatus\"O\n" +
	"\x19UpdateAuditStatusResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xa0\x02\n" +
	"\vCommentInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x1f\n" +
	"\vactivity_id\x18\x02 \x01(\x04R\n" +
	"activityId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x04R\x06userId\x12\x1b\n" +
	"\tparent_id\x18\x04 \x01(\x04R\bparentId\x12\x18\n" +
	"\acontent\x18\x05 \x01(\tR\acontent\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12!\n" +
	"\faudit_status\x18\a \x01(\x05R\vauditStatus\x12\x1a\n" +
	"\bnickname\x18\b \x01(\tR\bnickname\x12\x16\n" +
	"\x06avatar\x18\t \x01(\tR\x06avatar\"\x87\x01\n" +
	"\x14CreateCommentRequest\x12\x1f\n" +
	"\vactivity_id\x18\x01 \x01(\x04R\n" +
	"activityId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x04R\x06userId\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x1b\n" +
	"\tparent_id\x18\x04 \x01(\x04R\bparentId\"6\n" +
	"\x15CreateCommentResponse\x12\x1d\n" +
	"\n" +
	"comment_id\x18\x01 \x01(\x04R\tcommentId\"\xa9\x01\n" +
	"\x12GetCommentsRequest\x12\x1f\n" +
	"\vactivity_id\x18\x01 \x01(\x04R\n" +
	"activityId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\x12$\n" +
	"\x0eviewer_user_id\x18\x04 \x01(\x04R\fviewerUserId\x12\x1b\n" +
	"\tparent_id\x18\x05 \x01(\x04R\bparentId\"^\n" +
	"\x13GetCommentsResponse\x121\n" +
	"\bcomments\x18\x01 \x03(\v2\x15.activity.CommentInfoR\bcomments\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"c\n" +
	"\x1fUpdateCommentAuditStatusRequest\x12\x1d\n" +
	"\n" +
	"comment_id\x18\x01 \x01(\x04R\tcommentId\x12!\n" +
	"\faudit_status\x18\x02 \x01(\x05R\vauditStatus\"V\n" +
	" UpdateCommentAuditStatusResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"b\n" +
	"\x16GetMyActivitiesRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"h\n" +
	"\x1cGetEnrolledActivitiesRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"\xf2\x01\n" +
	"\x0fParticipantInfo\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x1a\n" +
	"\bnickname\x18\x02 \x01(\tR\bnickname\x12\x16\n" +
	"\x06avatar\x18\x03 \x01(\tR\x06avatar\x12;\n" +
	"\venroll_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"enrollTime\x12=\n" +
	"\fcheckin_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\vcheckinTime\x12\x16\n" +
	"\x06status\x18\x06 \x01(\x05R\x06status\"j\n" +
	"\x16GetParticipantsRequest\x12\x1f\n" +
	"\vactivity_id\x18\x01 \x01(\x04R\n" +
	"activityId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"n\n" +
	"\x17GetParticipantsResponse\x12=\n" +
	"\fparticipants\x18\x01 \x03(\v2\x19.activity.ParticipantInfoR\fparticipants\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total2\xb9\t\n" +
	"\bActivity\x12I\n" +
	"\x0eCreateActivity\x12\x1f.activity.CreateActivityRequest\x1a\x16.activity.ActivityInfo\x12V\n" +
	"\x0fGetActivityList\x12 .activity.GetActivityListRequest\x1a!.activity.GetActivityListResponse\x12O\n" +
	"\x11GetActivityDetail\x12\".activity.GetActivityDetailRequest\x1a\x16.activity.ActivityInfo\x12S\n" +
	"\x0eEnrollActivity\x12\x1f.activity.EnrollActivityRequest\x1a .activity.EnrollActivityResponse\x12O\n" +
	"\fCancelEnroll\x12\x1d.activity.CancelEnrollRequest\x1a .activity.EnrollActivityResponse\x12E\n" +
	"\aCheckIn\x12\x18.activity.CheckInRequest\x1a .activity.EnrollActivityResponse\x12I\n" +
	"\x0eUpdateActivity\x12\x1f.activity.UpdateActivityRequest\x1a\x16.activity.ActivityInfo\x12\\\n" +
	"\x11UpdateAuditStatus\x12\".activity.UpdateAuditStatusRequest\x1a#.activity.UpdateAuditStatusResponse\x12P\n" +
	"\rCreateComment\x12\x1e.activity.CreateCommentRequest\x1a\x1f.activity.CreateCommentResponse\x12J\n" +
	"\vGetComments\x12\x1c.activity.GetCommentsRequest\x1a\x1d.activity.GetCommentsResponse\x12q\n" +
	"\x18UpdateCommentAuditStatus\x12).activity.UpdateCommentAuditStatusRequest\x1a*.activity.UpdateCommentAuditStatusResponse\x12V\n" +
	"\x0fGetMyActivities\x12 .activity.GetMyActivitiesRequest\x1a!.activity.GetActivityListResponse\x12b\n" +
	"\x15GetEnrolledActivities\x12&.activity.GetEnrolledActivitiesRequest\x1a!.activity.GetActivityListResponse\x12V\n" +
	"\x0fGetParticipants\x12 .activity.GetParticipantsRequest\x1a!.activity.GetParticipantsResponseB\fZ\n" +
	"./activityb\x06proto3"

var (
	file_activity_activity_proto_rawDescOnce sync.Once
	file_activity_activity_proto_rawDescData []byte
)

func file_activity_activity_proto_rawDescGZIP() []byte {
	file_activity_activity_proto_rawDescOnce.Do(func() {
		file_activity_activity_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_activity_activity_proto_rawDesc), len(file_activity_activity_proto_rawDesc)))
	})
	return file_activity_activity_proto_rawDescData
}

var file_activity_activity_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_activity_activity_proto_goTypes = []any{
	(*ActivityInfo)(nil),                     // 0: activity.ActivityInfo
	(*CreateActivityRequest)(nil),            // 1: activity.CreateActivityRequest
	(*GetActivityListRequest)(nil),           // 2: activity.GetActivityListRequest
	(*GetActivityListResponse)(nil),          // 3: activity.GetActivityListResponse
	(*GetActivityDetailRequest)(nil),         // 4: activity.GetActivityDetailRequest
	(*EnrollActivityRequest)(nil),            // 5: activity.EnrollActivityRequest
	(*EnrollActivityResponse)(nil),           // 6: activity.EnrollActivityResponse
	(*CancelEnrollRequest)(nil),              // 7: activity.CancelEnrollRequest
	(*CheckInRequest)(nil),                   // 8: activity.CheckInRequest
	(*UpdateActivityRequest)(nil),            // 9: activity.UpdateActivityRequest
	(*UpdateAuditStatusRequest)(nil),         // 10: activity.UpdateAuditStatusRequest
	(*UpdateAuditStatusResponse)(nil),        // 11: activity.UpdateAuditStatusResponse
	(*CommentInfo)(nil),                      // 12: activity.CommentInfo
	(*CreateCommentRequest)(nil),             // 13: activity.CreateCommentRequest
	(*CreateCommentResponse)(nil),            // 14: activity.CreateCommentResponse
	(*GetCommentsRequest)(nil),               // 15: activity.GetCommentsRequest
	(*GetCommentsResponse)(nil),              // 16: activity.GetCommentsResponse
	(*UpdateCommentAuditStatusRequest)(nil),  // 17: activity.UpdateCommentAuditStatusRequest
	(*UpdateCommentAuditStatusResponse)(nil), // 18: activity.UpdateCommentAuditStatusResponse
	(*GetMyActivitiesRequest)(nil),           // 19: activity.GetMyActivitiesRequest
	(*GetEnrolledActivitiesRequest)(nil),     // 20: activity.GetEnrolledActivitiesRequest
	(*ParticipantInfo)(nil),                  // 21: activity.ParticipantInfo
	(*GetParticipantsRequest)(nil),           // 22: activity.GetParticipantsRequest
	(*GetParticipantsResponse)(nil),          // 23: activity.GetParticipantsResponse
	(*timestamppb.Timestamp)(nil),            // 24: google.protobuf.Timestamp
}
var file_activity_activity_proto_depIdxs = []int32{
	24, // 0: activity.ActivityInfo.start_time:type_name -> google.protobuf.Timestamp
	24, // 1: activity.ActivityInfo.end_time:type_name -> google.protobuf.Timestamp
	24, // 2: activity.ActivityInfo.created_at:type_name -> google.protobuf.Timestamp
	24, // 3: activity.CreateActivityRequest.start_time:type_name -> google.protobuf.Timestamp
	24, // 4: activity.CreateActivityRequest.end_time:type_name -> google.protobuf.Timestamp
	0,  // 5: activity.GetActivityListResponse.activities:type_name -> activity.ActivityInfo
	24, // 6: activity.UpdateActivityRequest.start_time:type_name -> google.protobuf.Timestamp
	24, // 7: activity.UpdateActivityRequest.end_time:type_name -> google.protobuf.Timestamp
	24, // 8: activity.CommentInfo.created_at:type_name -> google.protobuf.Timestamp
	12, // 9: activity.GetCommentsResponse.comments:type_name -> activity.CommentInfo
	24, // 10: activity.ParticipantInfo.enroll_time:type_name -> google.protobuf.Timestamp
	24, // 11: activity.ParticipantInfo.checkin_time:type_name -> google.protobuf.Timestamp
	21, // 12: activity.GetParticipantsResponse.participants:type_name -> activity.ParticipantInfo
	1,  // 13: activity.Activity.CreateActivity:input_type -> activity.CreateActivityRequest
	2,  // 14: activity.Activity.GetActivityList:input_type -> activity.GetActivityListRequest
	4,  // 15: activity.Activity.GetActivityDetail:input_type -> activity.GetActivityDetailRequest
	5,  // 16: activity.Activity.EnrollActivity:input_type -> activity.EnrollActivityRequest
	7,  // 17: activity.Activity.CancelEnroll:input_type -> activity.CancelEnrollRequest
	8,  // 18: activity.Activity.CheckIn:input_type -> activity.CheckInRequest
	9,  // 19: activity.Activity.UpdateActivity:input_type -> activity.UpdateActivityRequest
	10, // 20: activity.Activity.UpdateAuditStatus:input_type -> activity.UpdateAuditStatusRequest
	13, // 21: activity.Activity.CreateComment:input_type -> activity.CreateCommentRequest
	15, // 22: activity.Activity.GetComments:input_type -> activity.GetCommentsRequest
	17, // 23: activity.Activity.UpdateCommentAuditStatus:input_type -> activity.UpdateCommentAuditStatusRequest
	19, // 24: activity.Activity.GetMyActivities:input_type -> activity.GetMyActivitiesRequest
	20, // 25: activity.Activity.GetEnrolledActivities:input_type -> activity.GetEnrolledActivitiesRequest
	22, // 26: activity.Activity.GetParticipants:input_type -> activity.GetParticipantsRequest
	0,  // 27: activity.Activity.CreateActivity:output_type -> activity.ActivityInfo
	3,  // 28: activity.Activity.GetActivityList:output_type -> activity.GetActivityListResponse
	0,  // 29: activity.Activity.GetActivityDetail:output_type -> activity.ActivityInfo
	6,  // 30: activity.Activity.EnrollActivity:output_type -> activity.EnrollActivityResponse
	6,  // 31: activity.Activity.CancelEnroll:output_type -> activity.EnrollActivityResponse
	6,  // 32: activity.Activity.CheckIn:output_type -> activity.EnrollActivityResponse
	0,  // 33: activity.Activity.UpdateActivity:output_type -> activity.ActivityInfo
	11, // 34: activity.Activity.UpdateAuditStatus:output_type -> activity.UpdateAuditStatusResponse
	14, // 35: activity.Activity.CreateComment:output_type -> activity.CreateCommentResponse
	16, // 36: activity.Activity.GetComments:output_type -> activity.GetCommentsResponse
	18, // 37: activity.Activity.UpdateCommentAuditStatus:output_type -> activity.UpdateCommentAuditStatusResponse
	3,  // 38: activity.Activity.GetMyActivities:output_type -> activity.GetActivityListResponse
	3,  // 39: activity.Activity.GetEnrolledActivities:output_type -> activity.GetActivityListResponse
	23, // 40: activity.Activity.GetParticipants:output_type -> activity.GetParticipantsResponse
	27, // [27:41] is the sub-list for method output_type
	13, // [13:27] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_activity_activity_proto_init() }
func file_activity_activity_proto_init() {
	if File_activity_activity_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_activity_activity_proto_rawDesc), len(file_activity_activity_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_activity_activity_proto_goTypes,
		DependencyIndexes: file_activity_activity_proto_depIdxs,
		MessageInfos:      file_activity_activity_proto_msgTypes,
	}.Build()
	File_activity_activity_proto = out.File
	file_activity_activity_proto_goTypes = nil
	file_activity_activity_proto_depIdxs = nil
}
