// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	"pallink/gateway/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/user/login",
				Handler: LoginHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/activity/public/list",
				Handler: GetPublicActivityListHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/activity/public/detail",
				Handler: GetPublicActivityDetailHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/activity/public/comment/list",
				Handler: GetPublicCommentsHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/register",
				Handler: RegisterHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/im/ws",
				Handler: ImWsHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/activity/create",
				Handler: CreateActivityHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/activity/list",
				Handler: GetActivityListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/activity/update",
				Handler: UpdateActivityHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/activity/detail",
				Handler: GetActivityDetailHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/activity/checkIn",
				Handler: CheckInHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/activity/enroll",
				Handler: EnrollActivityHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/activity/cancelEnroll",
				Handler: CancelEnrollHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/activity/comment/create",
				Handler: CreateCommentHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/activity/participants",
				Handler: GetParticipantsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/activity/enrolled",
				Handler: GetEnrolledActivitiesHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/activity/my",
				Handler: GetMyActivitiesHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/user/me",
				Handler: GetUserInfoHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/update",
				Handler: UpdateUserInfoHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/notify/list",
				Handler: GetNotificationsHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/notify/read",
				Handler: MarkReadHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/im/conversation/open",
				Handler: OpenConversationHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/im/conversation/list",
				Handler: GetConversationListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/im/message/send",
				Handler: SendMessageHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/im/message/list",
				Handler: GetMessagesHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/im/conversation/read",
				Handler: MarkConversationReadHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)
}
