// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	"pallink/activity/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/activities",
				Handler: CreateActivityHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/activities",
				Handler: GetActivityListHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/activities/:id",
				Handler: UpdateActivityHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/activities/:id",
				Handler: GetActivityDetailHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/activities/:id/checkins",
				Handler: CheckInHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/activities/:id/enrollments",
				Handler: EnrollActivityHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/activities/:id/enrollments",
				Handler: CancelEnrollHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/activities/:id/participants",
				Handler: GetParticipantsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/activities/enrolled",
				Handler: GetEnrolledActivitiesHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/activities/my",
				Handler: GetMyActivitiesHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/public/activities",
				Handler: GetPublicActivityListHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/public/activities/:id",
				Handler: GetPublicActivityDetailHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)
}
