// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type ActivityBrief struct {
	Id            uint64 `json:"id"`
	CreatorId     uint64 `json:"creator_id"`
	CreatorName   string `json:"creator_name"`
	CreatorAvatar string `json:"creator_avatar"`
	Title         string `json:"title"`
	Location      string `json:"location"`
	StartTime     int64  `json:"start_time"`
	EndTime       int64  `json:"end_time"`
	MaxPeople     int32  `json:"max_people"`
	CurrentPeople int32  `json:"current_people"`
	Status        int32  `json:"status"`
	IsEnrolled    bool   `json:"is_enrolled"`
}

type ActivityInfo struct {
	Id            uint64 `json:"id"`
	CreatorId     uint64 `json:"creator_id"`
	Title         string `json:"title"`
	Description   string `json:"description"`
	Location      string `json:"location"`
	StartTime     int64  `json:"start_time"`
	EndTime       int64  `json:"end_time"`
	MaxPeople     int32  `json:"max_people"`
	CurrentPeople int32  `json:"current_people"`
	Status        int32  `json:"status"`
	CreatedAt     int64  `json:"created_at"`
	IsEnrolled    bool   `json:"is_enrolled"`
	CreatorName   string `json:"creator_name"`
	CreatorAvatar string `json:"creator_avatar"`
}

type CancelEnrollReq struct {
	Id uint64 `json:"id"`
}

type CancelEnrollResp struct {
	Success bool   `json:"success"`
	Message string `json:"message"`
}

type CheckInReq struct {
	Id   uint64 `json:"id"`
	Code string `json:"code,optional"`
}

type CheckInResp struct {
	Success bool   `json:"success"`
	Message string `json:"message"`
}

type CreateActivityReq struct {
	Title       string `json:"title"`
	Description string `json:"description"`
	Location    string `json:"location"`
	StartTime   int64  `json:"start_time"`
	EndTime     int64  `json:"end_time"`
	MaxPeople   int32  `json:"max_people,optional"`
}

type CreateActivityResp struct {
	Activity ActivityInfo `json:"activity"`
}

type EnrollActivityReq struct {
	Id uint64 `json:"id"`
}

type EnrollActivityResp struct {
	Success bool   `json:"success"`
	Message string `json:"message"`
}

type GetActivityDetailReq struct {
	Id uint64 `form:"id"`
}

type GetActivityDetailResp struct {
	Activity ActivityInfo `json:"activity"`
}

type GetActivityListReq struct {
	Page     int32  `form:"page,default=1"`
	PageSize int32  `form:"page_size,default=20"`
	Status   int32  `form:"status,optional"`
	Keyword  string `form:"keyword,optional"`
}

type GetActivityListResp struct {
	List     []ActivityBrief `json:"list"`
	Total    int32           `json:"total"`
	Page     int32           `json:"page"`
	PageSize int32           `json:"page_size"`
}

type GetEnrolledActivitiesReq struct {
	Page     int32 `form:"page,default=1"`
	PageSize int32 `form:"page_size,default=20"`
}

type GetEnrolledActivitiesResp struct {
	List     []ActivityBrief `json:"list"`
	Total    int32           `json:"total"`
	Page     int32           `json:"page"`
	PageSize int32           `json:"page_size"`
}

type GetMyActivitiesReq struct {
	Page     int32 `form:"page,default=1"`
	PageSize int32 `form:"page_size,default=20"`
}

type GetMyActivitiesResp struct {
	List     []ActivityBrief `json:"list"`
	Total    int32           `json:"total"`
	Page     int32           `json:"page"`
	PageSize int32           `json:"page_size"`
}

type GetParticipantsReq struct {
	Id       uint64 `form:"id"`
	Page     int32  `form:"page,default=1"`
	PageSize int32  `form:"page_size,default=20"`
}

type GetParticipantsResp struct {
	List     []ParticipantInfo `json:"list"`
	Total    int32             `json:"total"`
	Page     int32             `json:"page"`
	PageSize int32             `json:"page_size"`
}

type GetUserInfoRequest struct {
}

type LoginRequest struct {
	Mobile   string `json:"mobile"`
	Password string `json:"password"`
}

type LoginResponse struct {
	UserId   uint64   `json:"user_id"`
	Token    string   `json:"token"`
	UserInfo UserInfo `json:"user_info"`
}

type ParticipantInfo struct {
	UserId      uint64 `json:"user_id"`
	Nickname    string `json:"nickname"`
	Avatar      string `json:"avatar"`
	EnrollTime  int64  `json:"enroll_time"`
	CheckinTime int64  `json:"checkin_time"`
	Status      int32  `json:"status"`
}

type RegisterRequest struct {
	Mobile     string `json:"mobile"`
	Password   string `json:"password"`
	Nickname   string `json:"nickname"`
	VerifyCode string `json:"verify_code"`
}

type RegisterResponse struct {
	UserId uint64 `json:"user_id"`
	Token  string `json:"token"`
}

type UpdateActivityReq struct {
	Id          uint64  `json:"id"`
	Title       *string `json:"title,optional"`
	Description *string `json:"description,optional"`
	Location    *string `json:"location,optional"`
	StartTime   *int64  `json:"start_time,optional"`
	EndTime     *int64  `json:"end_time,optional"`
	MaxPeople   *int32  `json:"max_people,optional"`
	Status      *int32  `json:"status,optional"`
}

type UpdateActivityResp struct {
	Activity ActivityInfo `json:"activity"`
}

type UserInfo struct {
	Id       uint64 `json:"id"`
	Mobile   string `json:"mobile"`
	Nickname string `json:"nickname"`
	Avatar   string `json:"avatar"`
}
