// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type ActivityBrief struct {
	Id            uint64 `json:"id"`
	CreatorId     uint64 `json:"creator_id"`
	CreatorName   string `json:"creator_name"`
	CreatorAvatar string `json:"creator_avatar"`
	Title         string `json:"title"`
	Location      string `json:"location"`
	StartTime     int64  `json:"start_time"`
	EndTime       int64  `json:"end_time"`
	MaxPeople     int32  `json:"max_people"`
	CurrentPeople int32  `json:"current_people"`
	Status        int32  `json:"status"`
	AuditStatus   int32  `json:"audit_status"`
	IsEnrolled    bool   `json:"is_enrolled"`
}

type ActivityInfo struct {
	Id            uint64 `json:"id"`
	CreatorId     uint64 `json:"creator_id"`
	Title         string `json:"title"`
	Description   string `json:"description"`
	Location      string `json:"location"`
	StartTime     int64  `json:"start_time"`
	EndTime       int64  `json:"end_time"`
	MaxPeople     int32  `json:"max_people"`
	CurrentPeople int32  `json:"current_people"`
	Status        int32  `json:"status"`
	AuditStatus   int32  `json:"audit_status"`
	CreatedAt     int64  `json:"created_at"`
	IsEnrolled    bool   `json:"is_enrolled"`
	CreatorName   string `json:"creator_name"`
	CreatorAvatar string `json:"creator_avatar"`
}

type CancelEnrollReq struct {
	Id uint64 `json:"id"`
}

type CancelEnrollResp struct {
	Success bool   `json:"success"`
	Message string `json:"message"`
}

type CheckInReq struct {
	Id   uint64 `json:"id"`
	Code string `json:"code,optional"`
}

type CheckInResp struct {
	Success bool   `json:"success"`
	Message string `json:"message"`
}

type CreateActivityReq struct {
	Title       string `json:"title"`
	Description string `json:"description"`
	Location    string `json:"location"`
	StartTime   int64  `json:"start_time"`
	EndTime     int64  `json:"end_time"`
	MaxPeople   int32  `json:"max_people,optional"`
}

type CreateActivityResp struct {
	Activity ActivityInfo `json:"activity"`
}

type EnrollActivityReq struct {
	Id uint64 `json:"id"`
}

type EnrollActivityResp struct {
	Success bool   `json:"success"`
	Message string `json:"message"`
}

type GetActivityDetailReq struct {
	Id uint64 `form:"id"`
}

type GetActivityDetailResp struct {
	Activity ActivityInfo `json:"activity"`
}

type GetActivityListReq struct {
	Page     int32  `form:"page,default=1"`
	PageSize int32  `form:"page_size,default=20"`
	Status   int32  `form:"status,optional"`
	Keyword  string `form:"keyword,optional"`
}

type GetActivityListResp struct {
	List     []ActivityBrief `json:"list"`
	Total    int32           `json:"total"`
	Page     int32           `json:"page"`
	PageSize int32           `json:"page_size"`
}

type GetEnrolledActivitiesReq struct {
	Page     int32 `form:"page,default=1"`
	PageSize int32 `form:"page_size,default=20"`
}

type GetEnrolledActivitiesResp struct {
	List     []ActivityBrief `json:"list"`
	Total    int32           `json:"total"`
	Page     int32           `json:"page"`
	PageSize int32           `json:"page_size"`
}

type GetMyActivitiesReq struct {
	Page     int32 `form:"page,default=1"`
	PageSize int32 `form:"page_size,default=20"`
}

type GetMyActivitiesResp struct {
	List     []ActivityBrief `json:"list"`
	Total    int32           `json:"total"`
	Page     int32           `json:"page"`
	PageSize int32           `json:"page_size"`
}

type GetParticipantsReq struct {
	Id       uint64 `form:"id"`
	Page     int32  `form:"page,default=1"`
	PageSize int32  `form:"page_size,default=20"`
}

type GetParticipantsResp struct {
	List     []ParticipantInfo `json:"list"`
	Total    int32             `json:"total"`
	Page     int32             `json:"page"`
	PageSize int32             `json:"page_size"`
}

type GetUserInfoRequest struct {
}

type UpdateUserRequest struct {
	Nickname string `json:"nickname,optional"`
	Avatar   string `json:"avatar,optional"`
}

type UpdateUserResponse struct {
	UserInfo UserInfo `json:"user_info"`
}

type LoginRequest struct {
	Mobile   string `json:"mobile"`
	Password string `json:"password"`
}

type LoginResponse struct {
	UserId   uint64   `json:"user_id"`
	Token    string   `json:"token"`
	UserInfo UserInfo `json:"user_info"`
}

type ParticipantInfo struct {
	UserId      uint64 `json:"user_id"`
	Nickname    string `json:"nickname"`
	Avatar      string `json:"avatar"`
	EnrollTime  int64  `json:"enroll_time"`
	CheckinTime int64  `json:"checkin_time"`
	Status      int32  `json:"status"`
}

type RegisterRequest struct {
	Mobile     string `json:"mobile"`
	Password   string `json:"password"`
	Nickname   string `json:"nickname"`
	VerifyCode string `json:"verify_code"`
}

type RegisterResponse struct {
	UserId uint64 `json:"user_id"`
	Token  string `json:"token"`
}

type CommentInfo struct {
	Id          uint64 `json:"id"`
	ActivityId  uint64 `json:"activity_id"`
	UserId      uint64 `json:"user_id"`
	ParentId    uint64 `json:"parent_id"`
	Content     string `json:"content"`
	CreatedAt   int64  `json:"created_at"`
	AuditStatus int32  `json:"audit_status"`
	Nickname    string `json:"nickname"`
	Avatar      string `json:"avatar"`
}

type CreateCommentReq struct {
	ActivityId uint64 `json:"activity_id"`
	Content    string `json:"content"`
	ParentId   uint64 `json:"parent_id,optional"`
}

type CreateCommentResp struct {
	CommentId uint64 `json:"comment_id"`
}

type GetCommentsReq struct {
	ActivityId uint64 `form:"activity_id"`
	ParentId   uint64 `form:"parent_id,optional"`
	Page       int32  `form:"page,default=1"`
	PageSize   int32  `form:"page_size,default=20"`
}

type GetCommentsResp struct {
	List     []CommentInfo `json:"list"`
	Total    int32         `json:"total"`
	Page     int32         `json:"page"`
	PageSize int32         `json:"page_size"`
}

type ConversationInfo struct {
	Id            uint64 `json:"id"`
	PeerUserId    uint64 `json:"peer_user_id"`
	PeerNickname  string `json:"peer_nickname"`
	PeerAvatar    string `json:"peer_avatar"`
	LastMessageId uint64 `json:"last_message_id"`
	LastSenderId  uint64 `json:"last_sender_id"`
	LastMessage   string `json:"last_message"`
	LastMessageAt int64  `json:"last_message_at"`
	UnreadCount   int32  `json:"unread_count"`
	CreatedAt     int64  `json:"created_at"`
}

type GetConversationListReq struct {
	Page     int32 `form:"page,default=1"`
	PageSize int32 `form:"page_size,default=20"`
}

type GetConversationListResp struct {
	List     []ConversationInfo `json:"list"`
	Total    int32              `json:"total"`
	Page     int32              `json:"page"`
	PageSize int32              `json:"page_size"`
}

type GetMessagesReq struct {
	ConversationId  uint64 `form:"conversation_id"`
	BeforeMessageId uint64 `form:"before_message_id,optional"`
	PageSize        int32  `form:"page_size,default=20"`
}

type GetMessagesResp struct {
	List     []MessageInfo `json:"list"`
	HasMore  bool          `json:"has_more"`
	PageSize int32         `json:"page_size"`
}

type GetNotificationsReq struct {
	Page       int32 `form:"page,default=1"`
	PageSize   int32 `form:"page_size,default=20"`
	UnreadOnly bool  `form:"unread_only,optional"`
}

type GetNotificationsResp struct {
	List     []NotificationInfo `json:"list"`
	Total    int32              `json:"total"`
	Page     int32              `json:"page"`
	PageSize int32              `json:"page_size"`
}

type MarkReadReq struct {
	NotificationId uint64 `json:"notification_id,optional"`
}

type MarkReadResp struct {
	Success bool   `json:"success"`
	Message string `json:"message"`
}

type MarkConversationReadReq struct {
	ConversationId uint64 `json:"conversation_id"`
	LastReadMsgId  uint64 `json:"last_read_msg_id,optional"`
}

type MarkConversationReadResp struct {
	Success       bool   `json:"success"`
	Message       string `json:"message"`
	LastReadMsgId uint64 `json:"last_read_msg_id"`
}

type MessageInfo struct {
	Id             uint64 `json:"id"`
	ConversationId uint64 `json:"conversation_id"`
	SenderId       uint64 `json:"sender_id"`
	Content        string `json:"content"`
	AuditStatus    int32  `json:"audit_status"`
	CreatedAt      int64  `json:"created_at"`
}

type NotificationInfo struct {
	Id         uint64 `json:"id"`
	UserId     uint64 `json:"user_id"`
	ActorId    uint64 `json:"actor_id"`
	Type       string `json:"type"`
	ActivityId uint64 `json:"activity_id"`
	CommentId  uint64 `json:"comment_id"`
	ParentId   uint64 `json:"parent_id"`
	Content    string `json:"content"`
	CreatedAt  int64  `json:"created_at"`
	ReadAt     int64  `json:"read_at"`
}

type UpdateActivityReq struct {
	Id          uint64  `json:"id"`
	Title       *string `json:"title,optional"`
	Description *string `json:"description,optional"`
	Location    *string `json:"location,optional"`
	StartTime   *int64  `json:"start_time,optional"`
	EndTime     *int64  `json:"end_time,optional"`
	MaxPeople   *int32  `json:"max_people,optional"`
	Status      *int32  `json:"status,optional"`
}

type UpdateActivityResp struct {
	Activity ActivityInfo `json:"activity"`
}

type UserInfo struct {
	Id       uint64 `json:"id"`
	Mobile   string `json:"mobile"`
	Nickname string `json:"nickname"`
	Avatar   string `json:"avatar"`
}

type OpenConversationReq struct {
	PeerUserId uint64 `json:"peer_user_id"`
}

type OpenConversationResp struct {
	Conversation ConversationInfo `json:"conversation"`
}

type SendMessageReq struct {
	PeerUserId uint64 `json:"peer_user_id"`
	Content    string `json:"content"`
}

type SendMessageResp struct {
	Message MessageInfo `json:"message"`
}
