// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: activity.proto

package server

import (
	"context"

	"pallink/activity/activity"
	"pallink/activity/internal/logic"
	"pallink/activity/internal/svc"
)

type ActivityServer struct {
	svcCtx *svc.ServiceContext
	activity.UnimplementedActivityServer
}

func NewActivityServer(svcCtx *svc.ServiceContext) *ActivityServer {
	return &ActivityServer{
		svcCtx: svcCtx,
	}
}

func (s *ActivityServer) CreateActivity(ctx context.Context, in *activity.CreateActivityRequest) (*activity.ActivityInfo, error) {
	l := logic.NewCreateActivityLogic(ctx, s.svcCtx)
	return l.CreateActivity(in)
}

func (s *ActivityServer) GetActivityList(ctx context.Context, in *activity.GetActivityListRequest) (*activity.GetActivityListResponse, error) {
	l := logic.NewGetActivityListLogic(ctx, s.svcCtx)
	return l.GetActivityList(in)
}

func (s *ActivityServer) GetActivityDetail(ctx context.Context, in *activity.GetActivityDetailRequest) (*activity.ActivityInfo, error) {
	l := logic.NewGetActivityDetailLogic(ctx, s.svcCtx)
	return l.GetActivityDetail(in)
}

func (s *ActivityServer) EnrollActivity(ctx context.Context, in *activity.EnrollActivityRequest) (*activity.EnrollActivityResponse, error) {
	l := logic.NewEnrollActivityLogic(ctx, s.svcCtx)
	return l.EnrollActivity(in)
}

func (s *ActivityServer) CancelEnroll(ctx context.Context, in *activity.CancelEnrollRequest) (*activity.EnrollActivityResponse, error) {
	l := logic.NewCancelEnrollLogic(ctx, s.svcCtx)
	return l.CancelEnroll(in)
}

func (s *ActivityServer) CheckIn(ctx context.Context, in *activity.CheckInRequest) (*activity.EnrollActivityResponse, error) {
	l := logic.NewCheckInLogic(ctx, s.svcCtx)
	return l.CheckIn(in)
}

func (s *ActivityServer) UpdateActivity(ctx context.Context, in *activity.UpdateActivityRequest) (*activity.ActivityInfo, error) {
	l := logic.NewUpdateActivityLogic(ctx, s.svcCtx)
	return l.UpdateActivity(in)
}

func (s *ActivityServer) UpdateAuditStatus(ctx context.Context, in *activity.UpdateAuditStatusRequest) (*activity.UpdateAuditStatusResponse, error) {
	l := logic.NewUpdateAuditStatusLogic(ctx, s.svcCtx)
	return l.UpdateAuditStatus(in)
}

func (s *ActivityServer) CreateComment(ctx context.Context, in *activity.CreateCommentRequest) (*activity.CreateCommentResponse, error) {
	l := logic.NewCreateCommentLogic(ctx, s.svcCtx)
	return l.CreateComment(in)
}

func (s *ActivityServer) GetComments(ctx context.Context, in *activity.GetCommentsRequest) (*activity.GetCommentsResponse, error) {
	l := logic.NewGetCommentsLogic(ctx, s.svcCtx)
	return l.GetComments(in)
}

func (s *ActivityServer) UpdateCommentAuditStatus(ctx context.Context, in *activity.UpdateCommentAuditStatusRequest) (*activity.UpdateCommentAuditStatusResponse, error) {
	l := logic.NewUpdateCommentAuditStatusLogic(ctx, s.svcCtx)
	return l.UpdateCommentAuditStatus(in)
}

func (s *ActivityServer) GetMyActivities(ctx context.Context, in *activity.GetMyActivitiesRequest) (*activity.GetActivityListResponse, error) {
	l := logic.NewGetMyActivitiesLogic(ctx, s.svcCtx)
	return l.GetMyActivities(in)
}

func (s *ActivityServer) GetEnrolledActivities(ctx context.Context, in *activity.GetEnrolledActivitiesRequest) (*activity.GetActivityListResponse, error) {
	l := logic.NewGetEnrolledActivitiesLogic(ctx, s.svcCtx)
	return l.GetEnrolledActivities(in)
}

func (s *ActivityServer) GetParticipants(ctx context.Context, in *activity.GetParticipantsRequest) (*activity.GetParticipantsResponse, error) {
	l := logic.NewGetParticipantsLogic(ctx, s.svcCtx)
	return l.GetParticipants(in)
}
