// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.19.4
// source: activity/rpc/activity.proto

package activity

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Activity_CreateActivity_FullMethodName    = "/activity.Activity/CreateActivity"
	Activity_GetActivityList_FullMethodName   = "/activity.Activity/GetActivityList"
	Activity_GetActivityDetail_FullMethodName = "/activity.Activity/GetActivityDetail"
	Activity_EnrollActivity_FullMethodName    = "/activity.Activity/EnrollActivity"
)

// ActivityClient is the client API for Activity service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ActivityClient interface {
	CreateActivity(ctx context.Context, in *CreateActivityRequest, opts ...grpc.CallOption) (*ActivityInfo, error)
	GetActivityList(ctx context.Context, in *GetActivityListRequest, opts ...grpc.CallOption) (*GetActivityListResponse, error)
	GetActivityDetail(ctx context.Context, in *GetActivityDetailRequest, opts ...grpc.CallOption) (*ActivityInfo, error)
	EnrollActivity(ctx context.Context, in *EnrollActivityRequest, opts ...grpc.CallOption) (*EnrollActivityResponse, error)
}

type activityClient struct {
	cc grpc.ClientConnInterface
}

func NewActivityClient(cc grpc.ClientConnInterface) ActivityClient {
	return &activityClient{cc}
}

func (c *activityClient) CreateActivity(ctx context.Context, in *CreateActivityRequest, opts ...grpc.CallOption) (*ActivityInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ActivityInfo)
	err := c.cc.Invoke(ctx, Activity_CreateActivity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *activityClient) GetActivityList(ctx context.Context, in *GetActivityListRequest, opts ...grpc.CallOption) (*GetActivityListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetActivityListResponse)
	err := c.cc.Invoke(ctx, Activity_GetActivityList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *activityClient) GetActivityDetail(ctx context.Context, in *GetActivityDetailRequest, opts ...grpc.CallOption) (*ActivityInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ActivityInfo)
	err := c.cc.Invoke(ctx, Activity_GetActivityDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *activityClient) EnrollActivity(ctx context.Context, in *EnrollActivityRequest, opts ...grpc.CallOption) (*EnrollActivityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnrollActivityResponse)
	err := c.cc.Invoke(ctx, Activity_EnrollActivity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ActivityServer is the server API for Activity service.
// All implementations must embed UnimplementedActivityServer
// for forward compatibility.
type ActivityServer interface {
	CreateActivity(context.Context, *CreateActivityRequest) (*ActivityInfo, error)
	GetActivityList(context.Context, *GetActivityListRequest) (*GetActivityListResponse, error)
	GetActivityDetail(context.Context, *GetActivityDetailRequest) (*ActivityInfo, error)
	EnrollActivity(context.Context, *EnrollActivityRequest) (*EnrollActivityResponse, error)
	mustEmbedUnimplementedActivityServer()
}

// UnimplementedActivityServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedActivityServer struct{}

func (UnimplementedActivityServer) CreateActivity(context.Context, *CreateActivityRequest) (*ActivityInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateActivity not implemented")
}
func (UnimplementedActivityServer) GetActivityList(context.Context, *GetActivityListRequest) (*GetActivityListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetActivityList not implemented")
}
func (UnimplementedActivityServer) GetActivityDetail(context.Context, *GetActivityDetailRequest) (*ActivityInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method GetActivityDetail not implemented")
}
func (UnimplementedActivityServer) EnrollActivity(context.Context, *EnrollActivityRequest) (*EnrollActivityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EnrollActivity not implemented")
}
func (UnimplementedActivityServer) mustEmbedUnimplementedActivityServer() {}
func (UnimplementedActivityServer) testEmbeddedByValue()                  {}

// UnsafeActivityServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ActivityServer will
// result in compilation errors.
type UnsafeActivityServer interface {
	mustEmbedUnimplementedActivityServer()
}

func RegisterActivityServer(s grpc.ServiceRegistrar, srv ActivityServer) {
	// If the following call panics, it indicates UnimplementedActivityServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Activity_ServiceDesc, srv)
}

func _Activity_CreateActivity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateActivityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActivityServer).CreateActivity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Activity_CreateActivity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActivityServer).CreateActivity(ctx, req.(*CreateActivityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Activity_GetActivityList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetActivityListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActivityServer).GetActivityList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Activity_GetActivityList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActivityServer).GetActivityList(ctx, req.(*GetActivityListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Activity_GetActivityDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetActivityDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActivityServer).GetActivityDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Activity_GetActivityDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActivityServer).GetActivityDetail(ctx, req.(*GetActivityDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Activity_EnrollActivity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnrollActivityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActivityServer).EnrollActivity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Activity_EnrollActivity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActivityServer).EnrollActivity(ctx, req.(*EnrollActivityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Activity_ServiceDesc is the grpc.ServiceDesc for Activity service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Activity_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "activity.Activity",
	HandlerType: (*ActivityServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateActivity",
			Handler:    _Activity_CreateActivity_Handler,
		},
		{
			MethodName: "GetActivityList",
			Handler:    _Activity_GetActivityList_Handler,
		},
		{
			MethodName: "GetActivityDetail",
			Handler:    _Activity_GetActivityDetail_Handler,
		},
		{
			MethodName: "EnrollActivity",
			Handler:    _Activity_EnrollActivity_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "activity/rpc/activity.proto",
}
