// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.4
// source: activity/rpc/activity.proto

package activity

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ActivityInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatorId     uint64                 `protobuf:"varint,2,opt,name=creator_id,json=creatorId,proto3" json:"creator_id,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Location      string                 `protobuf:"bytes,5,opt,name=location,proto3" json:"location,omitempty"`
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	MaxPeople     int32                  `protobuf:"varint,8,opt,name=max_people,json=maxPeople,proto3" json:"max_people,omitempty"`
	CurrentPeople int32                  `protobuf:"varint,9,opt,name=current_people,json=currentPeople,proto3" json:"current_people,omitempty"`
	Status        int32                  `protobuf:"varint,10,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivityInfo) Reset() {
	*x = ActivityInfo{}
	mi := &file_activity_rpc_activity_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivityInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivityInfo) ProtoMessage() {}

func (x *ActivityInfo) ProtoReflect() protoreflect.Message {
	mi := &file_activity_rpc_activity_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivityInfo.ProtoReflect.Descriptor instead.
func (*ActivityInfo) Descriptor() ([]byte, []int) {
	return file_activity_rpc_activity_proto_rawDescGZIP(), []int{0}
}

func (x *ActivityInfo) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ActivityInfo) GetCreatorId() uint64 {
	if x != nil {
		return x.CreatorId
	}
	return 0
}

func (x *ActivityInfo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ActivityInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ActivityInfo) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *ActivityInfo) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *ActivityInfo) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *ActivityInfo) GetMaxPeople() int32 {
	if x != nil {
		return x.MaxPeople
	}
	return 0
}

func (x *ActivityInfo) GetCurrentPeople() int32 {
	if x != nil {
		return x.CurrentPeople
	}
	return 0
}

func (x *ActivityInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ActivityInfo) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type CreateActivityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CreatorId     uint64                 `protobuf:"varint,1,opt,name=creator_id,json=creatorId,proto3" json:"creator_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Location      string                 `protobuf:"bytes,4,opt,name=location,proto3" json:"location,omitempty"`
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	MaxPeople     int32                  `protobuf:"varint,7,opt,name=max_people,json=maxPeople,proto3" json:"max_people,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateActivityRequest) Reset() {
	*x = CreateActivityRequest{}
	mi := &file_activity_rpc_activity_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateActivityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateActivityRequest) ProtoMessage() {}

func (x *CreateActivityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_activity_rpc_activity_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateActivityRequest.ProtoReflect.Descriptor instead.
func (*CreateActivityRequest) Descriptor() ([]byte, []int) {
	return file_activity_rpc_activity_proto_rawDescGZIP(), []int{1}
}

func (x *CreateActivityRequest) GetCreatorId() uint64 {
	if x != nil {
		return x.CreatorId
	}
	return 0
}

func (x *CreateActivityRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateActivityRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateActivityRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *CreateActivityRequest) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *CreateActivityRequest) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *CreateActivityRequest) GetMaxPeople() int32 {
	if x != nil {
		return x.MaxPeople
	}
	return 0
}

type GetActivityListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetActivityListRequest) Reset() {
	*x = GetActivityListRequest{}
	mi := &file_activity_rpc_activity_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetActivityListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActivityListRequest) ProtoMessage() {}

func (x *GetActivityListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_activity_rpc_activity_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActivityListRequest.ProtoReflect.Descriptor instead.
func (*GetActivityListRequest) Descriptor() ([]byte, []int) {
	return file_activity_rpc_activity_proto_rawDescGZIP(), []int{2}
}

func (x *GetActivityListRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetActivityListRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type GetActivityListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Activities    []*ActivityInfo        `protobuf:"bytes,1,rep,name=activities,proto3" json:"activities,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetActivityListResponse) Reset() {
	*x = GetActivityListResponse{}
	mi := &file_activity_rpc_activity_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetActivityListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActivityListResponse) ProtoMessage() {}

func (x *GetActivityListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_activity_rpc_activity_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActivityListResponse.ProtoReflect.Descriptor instead.
func (*GetActivityListResponse) Descriptor() ([]byte, []int) {
	return file_activity_rpc_activity_proto_rawDescGZIP(), []int{3}
}

func (x *GetActivityListResponse) GetActivities() []*ActivityInfo {
	if x != nil {
		return x.Activities
	}
	return nil
}

func (x *GetActivityListResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type GetActivityDetailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetActivityDetailRequest) Reset() {
	*x = GetActivityDetailRequest{}
	mi := &file_activity_rpc_activity_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetActivityDetailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActivityDetailRequest) ProtoMessage() {}

func (x *GetActivityDetailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_activity_rpc_activity_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActivityDetailRequest.ProtoReflect.Descriptor instead.
func (*GetActivityDetailRequest) Descriptor() ([]byte, []int) {
	return file_activity_rpc_activity_proto_rawDescGZIP(), []int{4}
}

func (x *GetActivityDetailRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type EnrollActivityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActivityId    uint64                 `protobuf:"varint,1,opt,name=activity_id,json=activityId,proto3" json:"activity_id,omitempty"`
	UserId        uint64                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrollActivityRequest) Reset() {
	*x = EnrollActivityRequest{}
	mi := &file_activity_rpc_activity_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollActivityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollActivityRequest) ProtoMessage() {}

func (x *EnrollActivityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_activity_rpc_activity_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollActivityRequest.ProtoReflect.Descriptor instead.
func (*EnrollActivityRequest) Descriptor() ([]byte, []int) {
	return file_activity_rpc_activity_proto_rawDescGZIP(), []int{5}
}

func (x *EnrollActivityRequest) GetActivityId() uint64 {
	if x != nil {
		return x.ActivityId
	}
	return 0
}

func (x *EnrollActivityRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type EnrollActivityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrollActivityResponse) Reset() {
	*x = EnrollActivityResponse{}
	mi := &file_activity_rpc_activity_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollActivityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollActivityResponse) ProtoMessage() {}

func (x *EnrollActivityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_activity_rpc_activity_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollActivityResponse.ProtoReflect.Descriptor instead.
func (*EnrollActivityResponse) Descriptor() ([]byte, []int) {
	return file_activity_rpc_activity_proto_rawDescGZIP(), []int{6}
}

func (x *EnrollActivityResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_activity_rpc_activity_proto protoreflect.FileDescriptor

const file_activity_rpc_activity_proto_rawDesc = "" +
	"\n" +
	"\x1bactivity/rpc/activity.proto\x12\bactivity\x1a\x1fgoogle/protobuf/timestamp.proto\"\x9c\x03\n" +
	"\fActivityInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x1d\n" +
	"\n" +
	"creator_id\x18\x02 \x01(\x04R\tcreatorId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1a\n" +
	"\blocation\x18\x05 \x01(\tR\blocation\x129\n" +
	"\n" +
	"start_time\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\x12\x1d\n" +
	"\n" +
	"max_people\x18\b \x01(\x05R\tmaxPeople\x12%\n" +
	"\x0ecurrent_people\x18\t \x01(\x05R\rcurrentPeople\x12\x16\n" +
	"\x06status\x18\n" +
	" \x01(\x05R\x06status\x129\n" +
	"\n" +
	"created_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\x9b\x02\n" +
	"\x15CreateActivityRequest\x12\x1d\n" +
	"\n" +
	"creator_id\x18\x01 \x01(\x04R\tcreatorId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1a\n" +
	"\blocation\x18\x04 \x01(\tR\blocation\x129\n" +
	"\n" +
	"start_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\x12\x1d\n" +
	"\n" +
	"max_people\x18\a \x01(\x05R\tmaxPeople\"I\n" +
	"\x16GetActivityListRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\"g\n" +
	"\x17GetActivityListResponse\x126\n" +
	"\n" +
	"activities\x18\x01 \x03(\v2\x16.activity.ActivityInfoR\n" +
	"activities\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"*\n" +
	"\x18GetActivityDetailRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"Q\n" +
	"\x15EnrollActivityRequest\x12\x1f\n" +
	"\vactivity_id\x18\x01 \x01(\x04R\n" +
	"activityId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x04R\x06userId\"2\n" +
	"\x16EnrollActivityResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xd3\x02\n" +
	"\bActivity\x12I\n" +
	"\x0eCreateActivity\x12\x1f.activity.CreateActivityRequest\x1a\x16.activity.ActivityInfo\x12V\n" +
	"\x0fGetActivityList\x12 .activity.GetActivityListRequest\x1a!.activity.GetActivityListResponse\x12O\n" +
	"\x11GetActivityDetail\x12\".activity.GetActivityDetailRequest\x1a\x16.activity.ActivityInfo\x12S\n" +
	"\x0eEnrollActivity\x12\x1f.activity.EnrollActivityRequest\x1a .activity.EnrollActivityResponseB\fZ\n" +
	"./activityb\x06proto3"

var (
	file_activity_rpc_activity_proto_rawDescOnce sync.Once
	file_activity_rpc_activity_proto_rawDescData []byte
)

func file_activity_rpc_activity_proto_rawDescGZIP() []byte {
	file_activity_rpc_activity_proto_rawDescOnce.Do(func() {
		file_activity_rpc_activity_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_activity_rpc_activity_proto_rawDesc), len(file_activity_rpc_activity_proto_rawDesc)))
	})
	return file_activity_rpc_activity_proto_rawDescData
}

var file_activity_rpc_activity_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_activity_rpc_activity_proto_goTypes = []any{
	(*ActivityInfo)(nil),             // 0: activity.ActivityInfo
	(*CreateActivityRequest)(nil),    // 1: activity.CreateActivityRequest
	(*GetActivityListRequest)(nil),   // 2: activity.GetActivityListRequest
	(*GetActivityListResponse)(nil),  // 3: activity.GetActivityListResponse
	(*GetActivityDetailRequest)(nil), // 4: activity.GetActivityDetailRequest
	(*EnrollActivityRequest)(nil),    // 5: activity.EnrollActivityRequest
	(*EnrollActivityResponse)(nil),   // 6: activity.EnrollActivityResponse
	(*timestamppb.Timestamp)(nil),    // 7: google.protobuf.Timestamp
}
var file_activity_rpc_activity_proto_depIdxs = []int32{
	7,  // 0: activity.ActivityInfo.start_time:type_name -> google.protobuf.Timestamp
	7,  // 1: activity.ActivityInfo.end_time:type_name -> google.protobuf.Timestamp
	7,  // 2: activity.ActivityInfo.created_at:type_name -> google.protobuf.Timestamp
	7,  // 3: activity.CreateActivityRequest.start_time:type_name -> google.protobuf.Timestamp
	7,  // 4: activity.CreateActivityRequest.end_time:type_name -> google.protobuf.Timestamp
	0,  // 5: activity.GetActivityListResponse.activities:type_name -> activity.ActivityInfo
	1,  // 6: activity.Activity.CreateActivity:input_type -> activity.CreateActivityRequest
	2,  // 7: activity.Activity.GetActivityList:input_type -> activity.GetActivityListRequest
	4,  // 8: activity.Activity.GetActivityDetail:input_type -> activity.GetActivityDetailRequest
	5,  // 9: activity.Activity.EnrollActivity:input_type -> activity.EnrollActivityRequest
	0,  // 10: activity.Activity.CreateActivity:output_type -> activity.ActivityInfo
	3,  // 11: activity.Activity.GetActivityList:output_type -> activity.GetActivityListResponse
	0,  // 12: activity.Activity.GetActivityDetail:output_type -> activity.ActivityInfo
	6,  // 13: activity.Activity.EnrollActivity:output_type -> activity.EnrollActivityResponse
	10, // [10:14] is the sub-list for method output_type
	6,  // [6:10] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_activity_rpc_activity_proto_init() }
func file_activity_rpc_activity_proto_init() {
	if File_activity_rpc_activity_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_activity_rpc_activity_proto_rawDesc), len(file_activity_rpc_activity_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_activity_rpc_activity_proto_goTypes,
		DependencyIndexes: file_activity_rpc_activity_proto_depIdxs,
		MessageInfos:      file_activity_rpc_activity_proto_msgTypes,
	}.Build()
	File_activity_rpc_activity_proto = out.File
	file_activity_rpc_activity_proto_goTypes = nil
	file_activity_rpc_activity_proto_depIdxs = nil
}
