// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type ActivityBrief struct {
	Id            uint64 `json:"id"`
	CreatorId     uint64 `json:"creator_id"`
	CreatorName   string `json:"creator_name"`
	CreatorAvatar string `json:"creator_avatar"`
	Title         string `json:"title"`
	Location      string `json:"location"`
	StartTime     int64  `json:"start_time"`
	EndTime       int64  `json:"end_time"`
	MaxPeople     int32  `json:"max_people"`
	CurrentPeople int32  `json:"current_people"`
	Status        int32  `json:"status"`
	IsEnrolled    bool   `json:"is_enrolled"`
}

type ActivityInfo struct {
	Id            uint64 `json:"id"`
	CreatorId     uint64 `json:"creator_id"`
	Title         string `json:"title"`
	Description   string `json:"description"`
	Location      string `json:"location"`
	StartTime     int64  `json:"start_time"`     // Unix时间戳
	EndTime       int64  `json:"end_time"`       // Unix时间戳
	MaxPeople     int32  `json:"max_people"`     // 最大人数，0表示不限
	CurrentPeople int32  `json:"current_people"` // 当前报名人数
	Status        int32  `json:"status"`         // 1:招募中 2:进行中 3:已结束 4:已取消
	CreatedAt     int64  `json:"created_at"`     // Unix时间戳
	IsEnrolled    bool   `json:"is_enrolled"`    // 当前用户是否已报名
	CreatorName   string `json:"creator_name"`   // 创建者昵称
	CreatorAvatar string `json:"creator_avatar"` // 创建者头像
}

type CancelEnrollReq struct {
	Id uint64 `path:"id"`
}

type CancelEnrollResp struct {
	Success bool   `json:"success"`
	Message string `json:"message"`
}

type CheckInReq struct {
	Id   uint64 `path:"id"`
	Code string `json:"code,optional"` // 签到码
}

type CheckInResp struct {
	Success bool   `json:"success"`
	Message string `json:"message"`
}

type CreateActivityReq struct {
	Title       string `json:"title"`
	Description string `json:"description"`
	Location    string `json:"location"`
	StartTime   int64  `json:"start_time"`
	EndTime     int64  `json:"end_time"`
	MaxPeople   int32  `json:"max_people,optional"` // 可选，默认0(不限)
}

type CreateActivityResp struct {
	Activity ActivityInfo `json:"activity"`
}

type EnrollActivityReq struct {
	Id uint64 `path:"id"`
}

type EnrollActivityResp struct {
	Success bool   `json:"success"`
	Message string `json:"message"`
}

type GetActivityDetailReq struct {
	Id uint64 `path:"id"`
}

type GetActivityDetailResp struct {
	Activity ActivityInfo `json:"activity"`
}

type GetActivityListReq struct {
	Page     int32  `form:"page,default=1"`
	PageSize int32  `form:"page_size,default=20"`
	Status   int32  `form:"status,optional"`  // 筛选状态
	Keyword  string `form:"keyword,optional"` // 搜索关键词
}

type GetActivityListResp struct {
	List     []ActivityBrief `json:"list"`
	Total    int32           `json:"total"`
	Page     int32           `json:"page"`
	PageSize int32           `json:"page_size"`
}

type GetEnrolledActivitiesReq struct {
	Page     int32 `form:"page,default=1"`
	PageSize int32 `form:"page_size,default=20"`
}

type GetEnrolledActivitiesResp struct {
	List     []ActivityBrief `json:"list"`
	Total    int32           `json:"total"`
	Page     int32           `json:"page"`
	PageSize int32           `json:"page_size"`
}

type GetMyActivitiesReq struct {
	Page     int32 `form:"page,default=1"`
	PageSize int32 `form:"page_size,default=20"`
}

type GetMyActivitiesResp struct {
	List     []ActivityBrief `json:"list"`
	Total    int32           `json:"total"`
	Page     int32           `json:"page"`
	PageSize int32           `json:"page_size"`
}

type GetParticipantsReq struct {
	Id       uint64 `path:"id"`
	Page     int32  `form:"page,default=1"`
	PageSize int32  `form:"page_size,default=20"`
}

type GetParticipantsResp struct {
	List     []ParticipantInfo `json:"list"`
	Total    int32             `json:"total"`
	Page     int32             `json:"page"`
	PageSize int32             `json:"page_size"`
}

type ParticipantInfo struct {
	UserId      uint64 `json:"user_id"`
	Nickname    string `json:"nickname"`
	Avatar      string `json:"avatar"`
	EnrollTime  int64  `json:"enroll_time"`
	CheckinTime int64  `json:"checkin_time"`
	Status      int32  `json:"status"` // 1:已报名 2:已签到
}

type UpdateActivityReq struct {
	Id          uint64  `path:"id"`
	Title       *string `json:"title,optional"`
	Description *string `json:"description,optional"`
	Location    *string `json:"location,optional"`
	StartTime   *int64  `json:"start_time,optional"`
	EndTime     *int64  `json:"end_time,optional"`
	MaxPeople   *int32  `json:"max_people,optional"`
	Status      *int32  `json:"status,optional"`
}

type UpdateActivityResp struct {
	Activity ActivityInfo `json:"activity"`
}
