// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.4
// source: im/im.proto

package im

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConversationInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	PeerUserId    uint64                 `protobuf:"varint,2,opt,name=peer_user_id,json=peerUserId,proto3" json:"peer_user_id,omitempty"`
	PeerNickname  string                 `protobuf:"bytes,3,opt,name=peer_nickname,json=peerNickname,proto3" json:"peer_nickname,omitempty"`
	PeerAvatar    string                 `protobuf:"bytes,4,opt,name=peer_avatar,json=peerAvatar,proto3" json:"peer_avatar,omitempty"`
	LastMessageId uint64                 `protobuf:"varint,5,opt,name=last_message_id,json=lastMessageId,proto3" json:"last_message_id,omitempty"`
	LastSenderId  uint64                 `protobuf:"varint,6,opt,name=last_sender_id,json=lastSenderId,proto3" json:"last_sender_id,omitempty"`
	LastMessage   string                 `protobuf:"bytes,7,opt,name=last_message,json=lastMessage,proto3" json:"last_message,omitempty"`
	LastMessageAt *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=last_message_at,json=lastMessageAt,proto3" json:"last_message_at,omitempty"`
	UnreadCount   int32                  `protobuf:"varint,9,opt,name=unread_count,json=unreadCount,proto3" json:"unread_count,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConversationInfo) Reset() {
	*x = ConversationInfo{}
	mi := &file_im_im_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConversationInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConversationInfo) ProtoMessage() {}

func (x *ConversationInfo) ProtoReflect() protoreflect.Message {
	mi := &file_im_im_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConversationInfo.ProtoReflect.Descriptor instead.
func (*ConversationInfo) Descriptor() ([]byte, []int) {
	return file_im_im_proto_rawDescGZIP(), []int{0}
}

func (x *ConversationInfo) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ConversationInfo) GetPeerUserId() uint64 {
	if x != nil {
		return x.PeerUserId
	}
	return 0
}

func (x *ConversationInfo) GetPeerNickname() string {
	if x != nil {
		return x.PeerNickname
	}
	return ""
}

func (x *ConversationInfo) GetPeerAvatar() string {
	if x != nil {
		return x.PeerAvatar
	}
	return ""
}

func (x *ConversationInfo) GetLastMessageId() uint64 {
	if x != nil {
		return x.LastMessageId
	}
	return 0
}

func (x *ConversationInfo) GetLastSenderId() uint64 {
	if x != nil {
		return x.LastSenderId
	}
	return 0
}

func (x *ConversationInfo) GetLastMessage() string {
	if x != nil {
		return x.LastMessage
	}
	return ""
}

func (x *ConversationInfo) GetLastMessageAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastMessageAt
	}
	return nil
}

func (x *ConversationInfo) GetUnreadCount() int32 {
	if x != nil {
		return x.UnreadCount
	}
	return 0
}

func (x *ConversationInfo) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type MessageInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ConversationId uint64                 `protobuf:"varint,2,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	SenderId       uint64                 `protobuf:"varint,3,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	Content        string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	AuditStatus    int32                  `protobuf:"varint,5,opt,name=audit_status,json=auditStatus,proto3" json:"audit_status,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MessageInfo) Reset() {
	*x = MessageInfo{}
	mi := &file_im_im_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageInfo) ProtoMessage() {}

func (x *MessageInfo) ProtoReflect() protoreflect.Message {
	mi := &file_im_im_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageInfo.ProtoReflect.Descriptor instead.
func (*MessageInfo) Descriptor() ([]byte, []int) {
	return file_im_im_proto_rawDescGZIP(), []int{1}
}

func (x *MessageInfo) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MessageInfo) GetConversationId() uint64 {
	if x != nil {
		return x.ConversationId
	}
	return 0
}

func (x *MessageInfo) GetSenderId() uint64 {
	if x != nil {
		return x.SenderId
	}
	return 0
}

func (x *MessageInfo) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *MessageInfo) GetAuditStatus() int32 {
	if x != nil {
		return x.AuditStatus
	}
	return 0
}

func (x *MessageInfo) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type OpenConversationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PeerUserId    uint64                 `protobuf:"varint,2,opt,name=peer_user_id,json=peerUserId,proto3" json:"peer_user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenConversationRequest) Reset() {
	*x = OpenConversationRequest{}
	mi := &file_im_im_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenConversationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenConversationRequest) ProtoMessage() {}

func (x *OpenConversationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_im_im_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenConversationRequest.ProtoReflect.Descriptor instead.
func (*OpenConversationRequest) Descriptor() ([]byte, []int) {
	return file_im_im_proto_rawDescGZIP(), []int{2}
}

func (x *OpenConversationRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *OpenConversationRequest) GetPeerUserId() uint64 {
	if x != nil {
		return x.PeerUserId
	}
	return 0
}

type GetConversationListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConversationListRequest) Reset() {
	*x = GetConversationListRequest{}
	mi := &file_im_im_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConversationListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConversationListRequest) ProtoMessage() {}

func (x *GetConversationListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_im_im_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConversationListRequest.ProtoReflect.Descriptor instead.
func (*GetConversationListRequest) Descriptor() ([]byte, []int) {
	return file_im_im_proto_rawDescGZIP(), []int{3}
}

func (x *GetConversationListRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetConversationListRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetConversationListRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type GetConversationListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*ConversationInfo    `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConversationListResponse) Reset() {
	*x = GetConversationListResponse{}
	mi := &file_im_im_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConversationListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConversationListResponse) ProtoMessage() {}

func (x *GetConversationListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_im_im_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConversationListResponse.ProtoReflect.Descriptor instead.
func (*GetConversationListResponse) Descriptor() ([]byte, []int) {
	return file_im_im_proto_rawDescGZIP(), []int{4}
}

func (x *GetConversationListResponse) GetList() []*ConversationInfo {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *GetConversationListResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type SendMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SenderId      uint64                 `protobuf:"varint,1,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	PeerUserId    uint64                 `protobuf:"varint,2,opt,name=peer_user_id,json=peerUserId,proto3" json:"peer_user_id,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageRequest) Reset() {
	*x = SendMessageRequest{}
	mi := &file_im_im_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageRequest) ProtoMessage() {}

func (x *SendMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_im_im_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageRequest.ProtoReflect.Descriptor instead.
func (*SendMessageRequest) Descriptor() ([]byte, []int) {
	return file_im_im_proto_rawDescGZIP(), []int{5}
}

func (x *SendMessageRequest) GetSenderId() uint64 {
	if x != nil {
		return x.SenderId
	}
	return 0
}

func (x *SendMessageRequest) GetPeerUserId() uint64 {
	if x != nil {
		return x.PeerUserId
	}
	return 0
}

func (x *SendMessageRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type GetMessagesRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UserId          uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ConversationId  uint64                 `protobuf:"varint,2,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	BeforeMessageId uint64                 `protobuf:"varint,3,opt,name=before_message_id,json=beforeMessageId,proto3" json:"before_message_id,omitempty"`
	PageSize        int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetMessagesRequest) Reset() {
	*x = GetMessagesRequest{}
	mi := &file_im_im_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessagesRequest) ProtoMessage() {}

func (x *GetMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_im_im_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessagesRequest.ProtoReflect.Descriptor instead.
func (*GetMessagesRequest) Descriptor() ([]byte, []int) {
	return file_im_im_proto_rawDescGZIP(), []int{6}
}

func (x *GetMessagesRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetMessagesRequest) GetConversationId() uint64 {
	if x != nil {
		return x.ConversationId
	}
	return 0
}

func (x *GetMessagesRequest) GetBeforeMessageId() uint64 {
	if x != nil {
		return x.BeforeMessageId
	}
	return 0
}

func (x *GetMessagesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type GetMessagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*MessageInfo         `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	HasMore       bool                   `protobuf:"varint,2,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMessagesResponse) Reset() {
	*x = GetMessagesResponse{}
	mi := &file_im_im_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessagesResponse) ProtoMessage() {}

func (x *GetMessagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_im_im_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessagesResponse.ProtoReflect.Descriptor instead.
func (*GetMessagesResponse) Descriptor() ([]byte, []int) {
	return file_im_im_proto_rawDescGZIP(), []int{7}
}

func (x *GetMessagesResponse) GetList() []*MessageInfo {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *GetMessagesResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

type MarkConversationReadRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ConversationId uint64                 `protobuf:"varint,2,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	LastReadMsgId  uint64                 `protobuf:"varint,3,opt,name=last_read_msg_id,json=lastReadMsgId,proto3" json:"last_read_msg_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MarkConversationReadRequest) Reset() {
	*x = MarkConversationReadRequest{}
	mi := &file_im_im_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkConversationReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkConversationReadRequest) ProtoMessage() {}

func (x *MarkConversationReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_im_im_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkConversationReadRequest.ProtoReflect.Descriptor instead.
func (*MarkConversationReadRequest) Descriptor() ([]byte, []int) {
	return file_im_im_proto_rawDescGZIP(), []int{8}
}

func (x *MarkConversationReadRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *MarkConversationReadRequest) GetConversationId() uint64 {
	if x != nil {
		return x.ConversationId
	}
	return 0
}

func (x *MarkConversationReadRequest) GetLastReadMsgId() uint64 {
	if x != nil {
		return x.LastReadMsgId
	}
	return 0
}

type MarkConversationReadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	LastReadMsgId uint64                 `protobuf:"varint,3,opt,name=last_read_msg_id,json=lastReadMsgId,proto3" json:"last_read_msg_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkConversationReadResponse) Reset() {
	*x = MarkConversationReadResponse{}
	mi := &file_im_im_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkConversationReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkConversationReadResponse) ProtoMessage() {}

func (x *MarkConversationReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_im_im_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkConversationReadResponse.ProtoReflect.Descriptor instead.
func (*MarkConversationReadResponse) Descriptor() ([]byte, []int) {
	return file_im_im_proto_rawDescGZIP(), []int{9}
}

func (x *MarkConversationReadResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *MarkConversationReadResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *MarkConversationReadResponse) GetLastReadMsgId() uint64 {
	if x != nil {
		return x.LastReadMsgId
	}
	return 0
}

var File_im_im_proto protoreflect.FileDescriptor

const file_im_im_proto_rawDesc = "" +
	"\n" +
	"\vim/im.proto\x12\x02im\x1a\x1fgoogle/protobuf/timestamp.proto\"\x9d\x03\n" +
	"\x10ConversationInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12 \n" +
	"\fpeer_user_id\x18\x02 \x01(\x04R\n" +
	"peerUserId\x12#\n" +
	"\rpeer_nickname\x18\x03 \x01(\tR\fpeerNickname\x12\x1f\n" +
	"\vpeer_avatar\x18\x04 \x01(\tR\n" +
	"peerAvatar\x12&\n" +
	"\x0flast_message_id\x18\x05 \x01(\x04R\rlastMessageId\x12$\n" +
	"\x0elast_sender_id\x18\x06 \x01(\x04R\flastSenderId\x12!\n" +
	"\flast_message\x18\a \x01(\tR\vlastMessage\x12B\n" +
	"\x0flast_message_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\rlastMessageAt\x12!\n" +
	"\funread_count\x18\t \x01(\x05R\vunreadCount\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xdb\x01\n" +
	"\vMessageInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12'\n" +
	"\x0fconversation_id\x18\x02 \x01(\x04R\x0econversationId\x12\x1b\n" +
	"\tsender_id\x18\x03 \x01(\x04R\bsenderId\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12!\n" +
	"\faudit_status\x18\x05 \x01(\x05R\vauditStatus\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"T\n" +
	"\x17OpenConversationRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12 \n" +
	"\fpeer_user_id\x18\x02 \x01(\x04R\n" +
	"peerUserId\"f\n" +
	"\x1aGetConversationListRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"]\n" +
	"\x1bGetConversationListResponse\x12(\n" +
	"\x04list\x18\x01 \x03(\v2\x14.im.ConversationInfoR\x04list\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"m\n" +
	"\x12SendMessageRequest\x12\x1b\n" +
	"\tsender_id\x18\x01 \x01(\x04R\bsenderId\x12 \n" +
	"\fpeer_user_id\x18\x02 \x01(\x04R\n" +
	"peerUserId\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\"\x9f\x01\n" +
	"\x12GetMessagesRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12'\n" +
	"\x0fconversation_id\x18\x02 \x01(\x04R\x0econversationId\x12*\n" +
	"\x11before_message_id\x18\x03 \x01(\x04R\x0fbeforeMessageId\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"U\n" +
	"\x13GetMessagesResponse\x12#\n" +
	"\x04list\x18\x01 \x03(\v2\x0f.im.MessageInfoR\x04list\x12\x19\n" +
	"\bhas_more\x18\x02 \x01(\bR\ahasMore\"\x88\x01\n" +
	"\x1bMarkConversationReadRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12'\n" +
	"\x0fconversation_id\x18\x02 \x01(\x04R\x0econversationId\x12'\n" +
	"\x10last_read_msg_id\x18\x03 \x01(\x04R\rlastReadMsgId\"{\n" +
	"\x1cMarkConversationReadResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12'\n" +
	"\x10last_read_msg_id\x18\x03 \x01(\x04R\rlastReadMsgId2\xf6\x02\n" +
	"\x02Im\x12E\n" +
	"\x10OpenConversation\x12\x1b.im.OpenConversationRequest\x1a\x14.im.ConversationInfo\x12V\n" +
	"\x13GetConversationList\x12\x1e.im.GetConversationListRequest\x1a\x1f.im.GetConversationListResponse\x126\n" +
	"\vSendMessage\x12\x16.im.SendMessageRequest\x1a\x0f.im.MessageInfo\x12>\n" +
	"\vGetMessages\x12\x16.im.GetMessagesRequest\x1a\x17.im.GetMessagesResponse\x12Y\n" +
	"\x14MarkConversationRead\x12\x1f.im.MarkConversationReadRequest\x1a .im.MarkConversationReadResponseB\x06Z\x04./imb\x06proto3"

var (
	file_im_im_proto_rawDescOnce sync.Once
	file_im_im_proto_rawDescData []byte
)

func file_im_im_proto_rawDescGZIP() []byte {
	file_im_im_proto_rawDescOnce.Do(func() {
		file_im_im_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_im_im_proto_rawDesc), len(file_im_im_proto_rawDesc)))
	})
	return file_im_im_proto_rawDescData
}

var file_im_im_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_im_im_proto_goTypes = []any{
	(*ConversationInfo)(nil),             // 0: im.ConversationInfo
	(*MessageInfo)(nil),                  // 1: im.MessageInfo
	(*OpenConversationRequest)(nil),      // 2: im.OpenConversationRequest
	(*GetConversationListRequest)(nil),   // 3: im.GetConversationListRequest
	(*GetConversationListResponse)(nil),  // 4: im.GetConversationListResponse
	(*SendMessageRequest)(nil),           // 5: im.SendMessageRequest
	(*GetMessagesRequest)(nil),           // 6: im.GetMessagesRequest
	(*GetMessagesResponse)(nil),          // 7: im.GetMessagesResponse
	(*MarkConversationReadRequest)(nil),  // 8: im.MarkConversationReadRequest
	(*MarkConversationReadResponse)(nil), // 9: im.MarkConversationReadResponse
	(*timestamppb.Timestamp)(nil),        // 10: google.protobuf.Timestamp
}
var file_im_im_proto_depIdxs = []int32{
	10, // 0: im.ConversationInfo.last_message_at:type_name -> google.protobuf.Timestamp
	10, // 1: im.ConversationInfo.created_at:type_name -> google.protobuf.Timestamp
	10, // 2: im.MessageInfo.created_at:type_name -> google.protobuf.Timestamp
	0,  // 3: im.GetConversationListResponse.list:type_name -> im.ConversationInfo
	1,  // 4: im.GetMessagesResponse.list:type_name -> im.MessageInfo
	2,  // 5: im.Im.OpenConversation:input_type -> im.OpenConversationRequest
	3,  // 6: im.Im.GetConversationList:input_type -> im.GetConversationListRequest
	5,  // 7: im.Im.SendMessage:input_type -> im.SendMessageRequest
	6,  // 8: im.Im.GetMessages:input_type -> im.GetMessagesRequest
	8,  // 9: im.Im.MarkConversationRead:input_type -> im.MarkConversationReadRequest
	0,  // 10: im.Im.OpenConversation:output_type -> im.ConversationInfo
	4,  // 11: im.Im.GetConversationList:output_type -> im.GetConversationListResponse
	1,  // 12: im.Im.SendMessage:output_type -> im.MessageInfo
	7,  // 13: im.Im.GetMessages:output_type -> im.GetMessagesResponse
	9,  // 14: im.Im.MarkConversationRead:output_type -> im.MarkConversationReadResponse
	10, // [10:15] is the sub-list for method output_type
	5,  // [5:10] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_im_im_proto_init() }
func file_im_im_proto_init() {
	if File_im_im_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_im_im_proto_rawDesc), len(file_im_im_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_im_im_proto_goTypes,
		DependencyIndexes: file_im_im_proto_depIdxs,
		MessageInfos:      file_im_im_proto_msgTypes,
	}.Build()
	File_im_im_proto = out.File
	file_im_im_proto_goTypes = nil
	file_im_im_proto_depIdxs = nil
}
