// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: activity.proto

package activityclient

import (
	"context"

	"pallink/activity/activity"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	ActivityInfo                 = activity.ActivityInfo
	CancelEnrollRequest          = activity.CancelEnrollRequest
	CheckInRequest               = activity.CheckInRequest
	CreateActivityRequest        = activity.CreateActivityRequest
	EnrollActivityRequest        = activity.EnrollActivityRequest
	EnrollActivityResponse       = activity.EnrollActivityResponse
	GetActivityDetailRequest     = activity.GetActivityDetailRequest
	GetActivityListRequest       = activity.GetActivityListRequest
	GetActivityListResponse      = activity.GetActivityListResponse
	GetEnrolledActivitiesRequest = activity.GetEnrolledActivitiesRequest
	GetMyActivitiesRequest       = activity.GetMyActivitiesRequest
	GetParticipantsRequest       = activity.GetParticipantsRequest
	GetParticipantsResponse      = activity.GetParticipantsResponse
	ParticipantInfo              = activity.ParticipantInfo
	UpdateActivityRequest        = activity.UpdateActivityRequest
	UpdateAuditStatusRequest     = activity.UpdateAuditStatusRequest
	UpdateAuditStatusResponse    = activity.UpdateAuditStatusResponse

	Activity interface {
		CreateActivity(ctx context.Context, in *CreateActivityRequest, opts ...grpc.CallOption) (*ActivityInfo, error)
		GetActivityList(ctx context.Context, in *GetActivityListRequest, opts ...grpc.CallOption) (*GetActivityListResponse, error)
		GetActivityDetail(ctx context.Context, in *GetActivityDetailRequest, opts ...grpc.CallOption) (*ActivityInfo, error)
		EnrollActivity(ctx context.Context, in *EnrollActivityRequest, opts ...grpc.CallOption) (*EnrollActivityResponse, error)
		CancelEnroll(ctx context.Context, in *CancelEnrollRequest, opts ...grpc.CallOption) (*EnrollActivityResponse, error)
		CheckIn(ctx context.Context, in *CheckInRequest, opts ...grpc.CallOption) (*EnrollActivityResponse, error)
		UpdateActivity(ctx context.Context, in *UpdateActivityRequest, opts ...grpc.CallOption) (*ActivityInfo, error)
		UpdateAuditStatus(ctx context.Context, in *UpdateAuditStatusRequest, opts ...grpc.CallOption) (*UpdateAuditStatusResponse, error)
		GetMyActivities(ctx context.Context, in *GetMyActivitiesRequest, opts ...grpc.CallOption) (*GetActivityListResponse, error)
		GetEnrolledActivities(ctx context.Context, in *GetEnrolledActivitiesRequest, opts ...grpc.CallOption) (*GetActivityListResponse, error)
		GetParticipants(ctx context.Context, in *GetParticipantsRequest, opts ...grpc.CallOption) (*GetParticipantsResponse, error)
	}

	defaultActivity struct {
		cli zrpc.Client
	}
)

func NewActivity(cli zrpc.Client) Activity {
	return &defaultActivity{
		cli: cli,
	}
}

func (m *defaultActivity) CreateActivity(ctx context.Context, in *CreateActivityRequest, opts ...grpc.CallOption) (*ActivityInfo, error) {
	client := activity.NewActivityClient(m.cli.Conn())
	return client.CreateActivity(ctx, in, opts...)
}

func (m *defaultActivity) GetActivityList(ctx context.Context, in *GetActivityListRequest, opts ...grpc.CallOption) (*GetActivityListResponse, error) {
	client := activity.NewActivityClient(m.cli.Conn())
	return client.GetActivityList(ctx, in, opts...)
}

func (m *defaultActivity) GetActivityDetail(ctx context.Context, in *GetActivityDetailRequest, opts ...grpc.CallOption) (*ActivityInfo, error) {
	client := activity.NewActivityClient(m.cli.Conn())
	return client.GetActivityDetail(ctx, in, opts...)
}

func (m *defaultActivity) EnrollActivity(ctx context.Context, in *EnrollActivityRequest, opts ...grpc.CallOption) (*EnrollActivityResponse, error) {
	client := activity.NewActivityClient(m.cli.Conn())
	return client.EnrollActivity(ctx, in, opts...)
}

func (m *defaultActivity) CancelEnroll(ctx context.Context, in *CancelEnrollRequest, opts ...grpc.CallOption) (*EnrollActivityResponse, error) {
	client := activity.NewActivityClient(m.cli.Conn())
	return client.CancelEnroll(ctx, in, opts...)
}

func (m *defaultActivity) CheckIn(ctx context.Context, in *CheckInRequest, opts ...grpc.CallOption) (*EnrollActivityResponse, error) {
	client := activity.NewActivityClient(m.cli.Conn())
	return client.CheckIn(ctx, in, opts...)
}

func (m *defaultActivity) UpdateActivity(ctx context.Context, in *UpdateActivityRequest, opts ...grpc.CallOption) (*ActivityInfo, error) {
	client := activity.NewActivityClient(m.cli.Conn())
	return client.UpdateActivity(ctx, in, opts...)
}

func (m *defaultActivity) UpdateAuditStatus(ctx context.Context, in *UpdateAuditStatusRequest, opts ...grpc.CallOption) (*UpdateAuditStatusResponse, error) {
	client := activity.NewActivityClient(m.cli.Conn())
	return client.UpdateAuditStatus(ctx, in, opts...)
}

func (m *defaultActivity) GetMyActivities(ctx context.Context, in *GetMyActivitiesRequest, opts ...grpc.CallOption) (*GetActivityListResponse, error) {
	client := activity.NewActivityClient(m.cli.Conn())
	return client.GetMyActivities(ctx, in, opts...)
}

func (m *defaultActivity) GetEnrolledActivities(ctx context.Context, in *GetEnrolledActivitiesRequest, opts ...grpc.CallOption) (*GetActivityListResponse, error) {
	client := activity.NewActivityClient(m.cli.Conn())
	return client.GetEnrolledActivities(ctx, in, opts...)
}

func (m *defaultActivity) GetParticipants(ctx context.Context, in *GetParticipantsRequest, opts ...grpc.CallOption) (*GetParticipantsResponse, error) {
	client := activity.NewActivityClient(m.cli.Conn())
	return client.GetParticipants(ctx, in, opts...)
}
