// Code generated by goctl. DO NOT EDIT.
// Source: notify.proto

package notifyclient

import (
	"context"

	"pallink/notify/notify"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	GetNotificationsRequest  = notify.GetNotificationsRequest
	GetNotificationsResponse = notify.GetNotificationsResponse
	MarkReadRequest          = notify.MarkReadRequest
	MarkReadResponse         = notify.MarkReadResponse
	NotificationInfo         = notify.NotificationInfo

	Notify interface {
		GetNotifications(ctx context.Context, in *GetNotificationsRequest, opts ...grpc.CallOption) (*GetNotificationsResponse, error)
		MarkRead(ctx context.Context, in *MarkReadRequest, opts ...grpc.CallOption) (*MarkReadResponse, error)
	}

	defaultNotify struct {
		cli zrpc.Client
	}
)

func NewNotify(cli zrpc.Client) Notify {
	return &defaultNotify{
		cli: cli,
	}
}

func (m *defaultNotify) GetNotifications(ctx context.Context, in *GetNotificationsRequest, opts ...grpc.CallOption) (*GetNotificationsResponse, error) {
	client := notify.NewNotifyClient(m.cli.Conn())
	return client.GetNotifications(ctx, in, opts...)
}

func (m *defaultNotify) MarkRead(ctx context.Context, in *MarkReadRequest, opts ...grpc.CallOption) (*MarkReadResponse, error) {
	client := notify.NewNotifyClient(m.cli.Conn())
	return client.MarkRead(ctx, in, opts...)
}
