// Code generated by goctl. DO NOT EDIT.
// Source: notify.proto

package server

import (
	"context"

	"pallink/notify/internal/logic"
	"pallink/notify/internal/svc"
	"pallink/notify/notify"
)

type NotifyServer struct {
	svcCtx *svc.ServiceContext
	notify.UnimplementedNotifyServer
}

func NewNotifyServer(svcCtx *svc.ServiceContext) *NotifyServer {
	return &NotifyServer{
		svcCtx: svcCtx,
	}
}

func (s *NotifyServer) GetNotifications(ctx context.Context, in *notify.GetNotificationsRequest) (*notify.GetNotificationsResponse, error) {
	l := logic.NewGetNotificationsLogic(ctx, s.svcCtx)
	return l.GetNotifications(in)
}

func (s *NotifyServer) MarkRead(ctx context.Context, in *notify.MarkReadRequest) (*notify.MarkReadResponse, error) {
	l := logic.NewMarkReadLogic(ctx, s.svcCtx)
	return l.MarkRead(in)
}
