// Code generated by goctl. DO NOT EDIT.
// Source: notification.proto

package notificationclient

import (
	"context"

	"pallink/notification/notification"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	GetNotificationsRequest  = notification.GetNotificationsRequest
	GetNotificationsResponse = notification.GetNotificationsResponse
	MarkReadRequest          = notification.MarkReadRequest
	MarkReadResponse         = notification.MarkReadResponse
	NotificationInfo         = notification.NotificationInfo

	Notification interface {
		GetNotifications(ctx context.Context, in *GetNotificationsRequest, opts ...grpc.CallOption) (*GetNotificationsResponse, error)
		MarkRead(ctx context.Context, in *MarkReadRequest, opts ...grpc.CallOption) (*MarkReadResponse, error)
	}

	defaultNotification struct {
		cli zrpc.Client
	}
)

func NewNotification(cli zrpc.Client) Notification {
	return &defaultNotification{
		cli: cli,
	}
}

func (m *defaultNotification) GetNotifications(ctx context.Context, in *GetNotificationsRequest, opts ...grpc.CallOption) (*GetNotificationsResponse, error) {
	client := notification.NewNotificationClient(m.cli.Conn())
	return client.GetNotifications(ctx, in, opts...)
}

func (m *defaultNotification) MarkRead(ctx context.Context, in *MarkReadRequest, opts ...grpc.CallOption) (*MarkReadResponse, error) {
	client := notification.NewNotificationClient(m.cli.Conn())
	return client.MarkRead(ctx, in, opts...)
}
