apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pallink-public
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
spec:
  ingressClassName: nginx
  rules:
    - host: api.localhost
      http:
        paths:
          - path: /swagger
            pathType: Prefix
            backend:
              service:
                name: swagger-ui
                port:
                  number: 8080
          - path: /docs
            pathType: Prefix
            backend:
              service:
                name: swagger-ui
                port:
                  number: 8080
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gateway-api
                port:
                  number: 8080
    - host: pghero.localhost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: pghero
                port:
                  number: 8080
    - host: prometheus.localhost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: prometheus
                port:
                  number: 9090
    - host: grafana.localhost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: grafana
                port:
                  number: 3000
    - host: rabbitmq.localhost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: rabbitmq
                port:
                  number: 15672
